### ISSUE TITLE
多nimbus时getClusterInfo挂掉

### ISSUE THREAD

**Issue by lancelotnull** [alibaba/jstorm#114]
使用bin/jstorm list或jstorm ui时，都会抛如下异常（单nimbus时不会出现）。是因为thrift版本问题吗？

[WARN 2015-09-03 14:18:48 o.a.t.s.AbstractNonblockingServer$FrameBuffer:522 pool-7-thread-26] Exception while invoking!
org.apache.thrift.protocol.TProtocolException: Required field 'uptime_secs' is unset! Struct:NimbusStat(host:10.94.190.37:8267, uptime_secs:null)
        at backtype.storm.generated.NimbusStat.validate(NimbusStat.java:379) ~[jstorm-core-2.0.4-SNAPSHOT.jar:na]
        at backtype.storm.generated.NimbusStat$NimbusStatStandardScheme.write(NimbusStat.java:445) ~[jstorm-core-2.0.4-SNAPSHOT.jar:na]
        at backtype.storm.generated.NimbusStat$NimbusStatStandardScheme.write(NimbusStat.java:407) ~[jstorm-core-2.0.4-SNAPSHOT.jar:na]
        at backtype.storm.generated.NimbusStat.write(NimbusStat.java:345) ~[jstorm-core-2.0.4-SNAPSHOT.jar:na]
        at backtype.storm.generated.NimbusSummary$NimbusSummaryStandardScheme.write(NimbusSummary.java:947) ~[jstorm-core-2.0.4-SNAPSHOT.jar:na]
        at backtype.storm.generated.NimbusSummary$NimbusSummaryStandardScheme.write(NimbusSummary.java:843) ~[jstorm-core-2.0.4-SNAPSHOT.jar:na]
        at backtype.storm.generated.NimbusSummary.write(NimbusSummary.java:732) ~[jstorm-core-2.0.4-SNAPSHOT.jar:na]
        at backtype.storm.generated.ClusterSummary$ClusterSummaryStandardScheme.write(ClusterSummary.java:609) ~[jstorm-core-2.0.4-SNAPSHOT.jar:na]
        at backtype.storm.generated.ClusterSummary$ClusterSummaryStandardScheme.write(ClusterSummary.java:535) ~[jstorm-core-2.0.4-SNAPSHOT.jar:na]
        at backtype.storm.generated.ClusterSummary.write(ClusterSummary.java:458) ~[jstorm-core-2.0.4-SNAPSHOT.jar:na]
        at backtype.storm.generated.Nimbus$getClusterInfo_result$getClusterInfo_resultStandardScheme.write(Nimbus.java:20262) ~[jstorm-core-2.0.4-SNAPSHOT.jar:na]
        at backtype.storm.generated.Nimbus$getClusterInfo_result$getClusterInfo_resultStandardScheme.write(Nimbus.java:20226) ~[jstorm-core-2.0.4-SNAPSHOT.jar:na]
        at backtype.storm.generated.Nimbus$getClusterInfo_result.write(Nimbus.java:20177) ~[jstorm-core-2.0.4-SNAPSHOT.jar:na]
        at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:53) ~[libthrift-0.9.2.jar:0.9.2]
        at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:39) ~[libthrift-0.9.2.jar:0.9.2]
        at org.apache.thrift.server.AbstractNonblockingServer$FrameBuffer.invoke(AbstractNonblockingServer.java:518) ~[libthrift-0.9.2.jar:0.9.2]
        at org.apache.thrift.server.Invocation.run(Invocation.java:18) [libthrift-0.9.2.jar:0.9.2]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110) [na:1.7.0_03-icedtea]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603) [na:1.7.0_03-icedtea]
        at java.lang.Thread.run(Thread.java:722) [na:1.7.0_03-icedtea]

**Comment by lancelotnull** [comment]
使用的是release包是http://42.121.19.155/jstorm/jstorm-2.0.4-SNAPSHOT.tar.gz

**Comment by longdafeng** [comment]
如果非常着急的话， 可以如下修改
不急的话，等下一个版本， 下一个版本， 9月20号前会release


--- a/jstorm-core/src/main/java/com/alibaba/jstorm/cluster/StormZkClusterState.java
+++ b/jstorm-core/src/main/java/com/alibaba/jstorm/cluster/StormZkClusterState.java
@@ -705,7 +705,7 @@ public class StormZkClusterState implements StormClusterState {
     public String get_nimbus_slave_time(String host) throws Exception {
         String path =
                 Cluster.NIMBUS_SLAVE_SUBTREE + Cluster.ZK_SEPERATOR + host;
-        return (String) getObject(path, false);
+        return (String) getString(path, false);
     }

发件人:  lancelot
答复:  alibaba/jstorm
日期:  2015年9月5日 星期六 下午3:03
至:  alibaba/jstorm
主题:  Re: [jstorm] 多nimbus时getClusterInfo挂掉 (#114)


使用的是release包是http://42.121.19.155/jstorm/jstorm-2.0.4-SNAPSHOT.tar.gz

**Comment by longdafeng** [comment]
fixed in 2.1.0
