### ISSUE TITLE
启动nimbus时报错

### ISSUE THREAD

**Issue by ecliar** [alibaba/jstorm#140]
[ERROR 2015-12-10 09:35:59 c.a.j.d.n.TopologyMetricsRunnable:496 TopologyMetricsRunnable] failed to sync remote meta
java.lang.NullPointerException: null
        at com.alibaba.jstorm.daemon.nimbus.TopologyMetricsRunnable.syncMetaFromRemote(TopologyMetricsRunnable.java:481) [jstorm-core-2.1.0.jar:na]
        at com.alibaba.jstorm.daemon.nimbus.TopologyMetricsRunnable.syncTopologyMeta(TopologyMetricsRunnable.java:439) [jstorm-core-2.1.0.jar:na]
        at com.alibaba.jstorm.daemon.nimbus.TopologyMetricsRunnable.handleRefreshEvent(TopologyMetricsRunnable.java:551) [jstorm-core-2.1.0.jar:na]
        at com.alibaba.jstorm.daemon.nimbus.TopologyMetricsRunnable.run(TopologyMetricsRunnable.java:262) [jstorm-core-2.1.0.jar:na]
[ERROR 2015-12-10 09:35:59 c.a.j.s.FollowerRunnable:89 main] get nimbus host error!
java.lang.Exception: the hostname which Nimbus get is localhost
        at com.alibaba.jstorm.schedule.FollowerRunnable.<init>(FollowerRunnable.java:86) ~[jstorm-core-2.1.0.jar:na]
        at com.alibaba.jstorm.daemon.nimbus.NimbusServer.initFollowerThread(NimbusServer.java:268) [jstorm-core-2.1.0.jar:na]
        at com.alibaba.jstorm.daemon.nimbus.NimbusServer.launchServer(NimbusServer.java:117) [jstorm-core-2.1.0.jar:na]
        at com.alibaba.jstorm.daemon.nimbus.NimbusServer.main(NimbusServer.java:91) [jstorm-core-2.1.0.jar:na]
[ERROR 2015-12-10 09:35:59 c.a.j.d.n.NimbusServer:130 main] Fail to run nimbus 
java.lang.RuntimeException: java.lang.Exception: the hostname which Nimbus get is localhost
        at com.alibaba.jstorm.schedule.FollowerRunnable.<init>(FollowerRunnable.java:90) ~[jstorm-core-2.1.0.jar:na]
        at com.alibaba.jstorm.daemon.nimbus.NimbusServer.initFollowerThread(NimbusServer.java:268) [jstorm-core-2.1.0.jar:na]
        at com.alibaba.jstorm.daemon.nimbus.NimbusServer.launchServer(NimbusServer.java:117) [jstorm-core-2.1.0.jar:na]
        at com.alibaba.jstorm.daemon.nimbus.NimbusServer.main(NimbusServer.java:91) [jstorm-core-2.1.0.jar:na]
Caused by: java.lang.Exception: the hostname which Nimbus get is localhost
        at com.alibaba.jstorm.schedule.FollowerRunnable.<init>(FollowerRunnable.java:86) ~[jstorm-core-2.1.0.jar:na]
        ... 3 common frames omitted
[INFO 2015-12-10 09:35:59 c.a.j.d.n.NimbusServer:290 main] Begin to shutdown nimbus
[ERROR 2015-12-10 09:35:59 c.a.j.d.n.TopologyMetricsRunnable:496 TopologyMetricsRunnable] failed to sync remote meta
java.lang.NullPointerException: null
        at com.alibaba.jstorm.daemon.nimbus.TopologyMetricsRunnable.syncMetaFromRemote(TopologyMetricsRunnable.java:481) [jstorm-core-2.1.0.jar:na]
        at com.alibaba.jstorm.daemon.nimbus.TopologyMetricsRunnable.syncTopologyMeta(TopologyMetricsRunnable.java:443) [jstorm-core-2.1.0.jar:na]
        at com.alibaba.jstorm.daemon.nimbus.TopologyMetricsRunnable.handleRefreshEvent(TopologyMetricsRunnable.java:551) [jstorm-core-2.1.0.jar:na]
        at com.alibaba.jstorm.daemon.nimbus.TopologyMetricsRunnable.run(TopologyMetricsRunnable.java:262) [jstorm-core-2.1.0.jar:na]

**Comment by wuchong** [comment]
集群模式下， nimbus.host 的配置不能是 localhost。

**Comment by ecliar** [comment]
![image](https://cloud.githubusercontent.com/assets/1331705/11705137/b6da5fec-9f28-11e5-815e-1779656fb46c.png)
我都已经设为别的机器IP了还是报错，而且supervisor也参和进来一起报了
[ERROR 2015-12-10 10:20:35 c.a.j.d.s.Heartbeat:100 main] get supervisor host error!
java.lang.Exception: the hostname which  supervisor get is localhost

**Comment by unsleepy22** [comment]
fixed~

**Comment by FavorMylikes** [comment]
Is it fixed ? I got this same problem too@ecliar

**Comment by unsleepy22** [comment]
Build with the latest master code, should be ok  @FavorMylikes
