### ISSUE TITLE
jstorm ui启动失败

### ISSUE THREAD

**Issue by NextMark** [alibaba/jstorm#147]
按官方文档指导方式启动jstorm ui一直失败，无法初始化log4j，如下
09-Dec-2015 19:13:10.510 WARNING [localhost-startStop-1] org.springframework.web.context.support.XmlWebApplicationContext.refresh Exception encountered during context initialization - cancelling refresh attempt
 org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'clusterAPIController' defined in file [/home/work/local/tomcat-jstorm-ui/webapps/jstorm-ui-2.1.0/WEB-INF/classes/com/alibaba/jstorm/ui/api/ClusterAPIController.class]: Instantiation of bean failed; nested exception is java.lang.NoClassDefFoundError: Could not initialize class org.apache.log4j.Log4jLoggerFactory
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1095)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1040)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:505)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:302)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:229)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:298)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:725)

解决办法：删除${jstorm-ui}/webapps/jstorm-ui-2.1.0/WEB-INF/lib/ 下的slf4j-log4j12-1.7.5.jar包

**Comment by unsleepy22** [comment]
这个应该是老的代码了，最新代码已经fix了这个问题。
