### ISSUE TITLE
jstorm 0.9.6.3 keeps resetting channel

### ISSUE THREAD

**Issue by zhjchen** [alibaba/jstorm#150]
Using jstorm 0.9.6.3, two workers.
See the following exceptions. First it failed to send requests, then it reseted channel and builded connection.
Any ideas?  

[WARN  2015-12-13 20:56:34 NettyClientAsync:141 BatchTupleRunable] Target server  /10.161.11.201:6801 is unavailable, pending 3, bufferSize 8388697, block sending 29189ms

[WARN  2015-12-13 20:56:34 NettyClientAsync:148 BatchTupleRunable] Target server  /10.161.11.201:6801 is unavailable, wait too much time, throw timeout message

[INFO  2015-12-13 20:56:34 NettyClient:386 BatchTupleRunable] Use new channel null replace old channel /10.161.11.230:50519

[INFO  2015-12-13 20:56:34 NettyClient:240 BatchTupleRunable] Failed to send requests to /10.161.11.201:6801: [id: 0x0ce74b67, /10.161.11.230:50519 :> /10.161.11.201:6801]:

java.nio.channels.ClosedChannelException

at org.jboss.netty.channel.socket.nio.AbstractNioWorker.cleanUpWriteBuffer(AbstractNioWorker.java:405)

at org.jboss.netty.channel.socket.nio.AbstractNioWorker.close(AbstractNioWorker.java:373)

at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink.eventSunk(NioClientSocketPipelineSink.java:58)

at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:779)

at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.handleDownstream(OneToOneEncoder.java:54)

at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591)

at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:582)

at org.jboss.netty.channel.Channels.close(Channels.java:812)

at org.jboss.netty.channel.AbstractChannel.close(AbstractChannel.java:197)

at com.alibaba.jstorm.message.netty.NettyClient.closeChannel(NettyClient.java:339)

at com.alibaba.jstorm.message.netty.NettyClient.setChannel(NettyClient.java:392)

at com.alibaba.jstorm.message.netty.NettyClientAsync.waitChannelReady(NettyClientAsync.java:153)

at com.alibaba.jstorm.message.netty.NettyClientAsync.handleFailedChannel(NettyClientAsync.java:208)

at com.alibaba.jstorm.message.netty.NettyClientAsync.pushBatch(NettyClientAsync.java:270)

at com.alibaba.jstorm.message.netty.NettyClientAsync.send(NettyClientAsync.java:122)

at com.alibaba.jstorm.daemon.worker.BatchTupleRunable.handleOneEvent(BatchTupleRunable.java:89)

at com.alibaba.jstorm.daemon.worker.BatchTupleRunable.handleEvent(BatchTupleRunable.java:119)

at com.alibaba.jstorm.utils.DisruptorRunable.onEvent(DisruptorRunable.java:54)

at backtype.storm.utils.DisruptorQueueImpl.consumeBatchToCursor(DisruptorQueueImpl.java:179)

at backtype.storm.utils.DisruptorQueueImpl.consumeBatchWhenAvailable(DisruptorQueueImpl.java:146)

at com.alibaba.jstorm.utils.DisruptorRunable.run(DisruptorRunable.java:68)

at com.alibaba.jstorm.callback.AsyncLoopRunnable.run(AsyncLoopRunnable.java:51)

at java.lang.Thread.run(Thread.java:745)

[INFO  2015-12-13 20:56:34 NettyClient:331 BatchTupleRunable] [id: 0x0ce74b67, /10.161.11.230:50519 :> /10.161.11.201:6801] is already closed

[INFO  2015-12-13 20:56:34 NettyClient:240 BatchTupleRunable] Failed to send requests to /10.161.11.201:6801: [id: 0x0ce74b67, /10.161.11.230:50519 :> /10.161.11.201:6801]:

java.nio.channels.ClosedChannelException

at org.jboss.netty.channel.socket.nio.AbstractNioWorker.cleanUpWriteBuffer(AbstractNioWorker.java:405)

at org.jboss.netty.channel.socket.nio.AbstractNioWorker.close(AbstractNioWorker.java:373)

at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink.eventSunk(NioClientSocketPipelineSink.java:58)

at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:779)

at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.handleDownstream(OneToOneEncoder.java:54)

at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591)

at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:582)

at org.jboss.netty.channel.Channels.close(Channels.java:812)

at org.jboss.netty.channel.AbstractChannel.close(AbstractChannel.java:197)

at com.alibaba.jstorm.message.netty.NettyClient.closeChannel(NettyClient.java:339)

at com.alibaba.jstorm.message.netty.NettyClient.setChannel(NettyClient.java:392)

at com.alibaba.jstorm.message.netty.NettyClientAsync.waitChannelReady(NettyClientAsync.java:153)

at com.alibaba.jstorm.message.netty.NettyClientAsync.handleFailedChannel(NettyClientAsync.java:208)

at com.alibaba.jstorm.message.netty.NettyClientAsync.pushBatch(NettyClientAsync.java:270)

at com.alibaba.jstorm.message.netty.NettyClientAsync.send(NettyClientAsync.java:122)

at com.alibaba.jstorm.daemon.worker.BatchTupleRunable.handleOneEvent(BatchTupleRunable.java:89)

at com.alibaba.jstorm.daemon.worker.BatchTupleRunable.handleEvent(BatchTupleRunable.java:119)

at com.alibaba.jstorm.utils.DisruptorRunable.onEvent(DisruptorRunable.java:54)

at backtype.storm.utils.DisruptorQueueImpl.consumeBatchToCursor(DisruptorQueueImpl.java:179)

at backtype.storm.utils.DisruptorQueueImpl.consumeBatchWhenAvailable(DisruptorQueueImpl.java:146)

at com.alibaba.jstorm.utils.DisruptorRunable.run(DisruptorRunable.java:68)

at com.alibaba.jstorm.callback.AsyncLoopRunnable.run(AsyncLoopRunnable.java:51)

at java.lang.Thread.run(Thread.java:745)

[INFO  2015-12-13 20:56:34 NettyClient:331 BatchTupleRunable] [id: 0x0ce74b67, /10.161.11.230:50519 :> /10.161.11.201:6801] is already closed

[INFO  2015-12-13 20:56:34 NettyClient:240 BatchTupleRunable] Failed to send requests to /10.161.11.201:6801: [id: 0x0ce74b67, /10.161.11.230:50519 :> /10.161.11.201:6801]:

java.nio.channels.ClosedChannelException

at org.jboss.netty.channel.socket.nio.AbstractNioWorker.cleanUpWriteBuffer(AbstractNioWorker.java:405)

at org.jboss.netty.channel.socket.nio.AbstractNioWorker.close(AbstractNioWorker.java:373)

at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink.eventSunk(NioClientSocketPipelineSink.java:58)

at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:779)

at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.handleDownstream(OneToOneEncoder.java:54)

at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591)

at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:582)

at org.jboss.netty.channel.Channels.close(Channels.java:812)

at org.jboss.netty.channel.AbstractChannel.close(AbstractChannel.java:197)

at com.alibaba.jstorm.message.netty.NettyClient.closeChannel(NettyClient.java:339)

at com.alibaba.jstorm.message.netty.NettyClient.setChannel(NettyClient.java:392)

at com.alibaba.jstorm.message.netty.NettyClientAsync.waitChannelReady(NettyClientAsync.java:153)

at com.alibaba.jstorm.message.netty.NettyClientAsync.handleFailedChannel(NettyClientAsync.java:208)

at com.alibaba.jstorm.message.netty.NettyClientAsync.pushBatch(NettyClientAsync.java:270)

at com.alibaba.jstorm.message.netty.NettyClientAsync.send(NettyClientAsync.java:122)

at com.alibaba.jstorm.daemon.worker.BatchTupleRunable.handleOneEvent(BatchTupleRunable.java:89)

at com.alibaba.jstorm.daemon.worker.BatchTupleRunable.handleEvent(BatchTupleRunable.java:119)

at com.alibaba.jstorm.utils.DisruptorRunable.onEvent(DisruptorRunable.java:54)

at backtype.storm.utils.DisruptorQueueImpl.consumeBatchToCursor(DisruptorQueueImpl.java:179)

at backtype.storm.utils.DisruptorQueueImpl.consumeBatchWhenAvailable(DisruptorQueueImpl.java:146)

at com.alibaba.jstorm.utils.DisruptorRunable.run(DisruptorRunable.java:68)

at com.alibaba.jstorm.callback.AsyncLoopRunnable.run(AsyncLoopRunnable.java:51)

at java.lang.Thread.run(Thread.java:745)

[INFO  2015-12-13 20:56:34 NettyClient:331 BatchTupleRunable] [id: 0x0ce74b67, /10.161.11.230:50519 :> /10.161.11.201:6801] is already closed

[INFO  2015-12-13 20:56:34 NettyClient:393 BatchTupleRunable] Successfully close old channel /10.161.11.230:50519

[WARN  2015-12-13 20:56:34 NettyClientAsync:154 BatchTupleRunable] Reset channel as null

[INFO  2015-12-13 20:56:34 NettyClient:166 ReconnectRunnable] Reconnect ... [1], /10.161.11.201:6801, sleep 100ms

[INFO  2015-12-13 20:56:34 StormClientHandler:71 Netty-Client-worker-1] Receive channelDisconnected to /10.161.11.201:6801, channel = [id: 0x0ce74b67, /10.161.11.230:50519 :> /10.161.11.201:6801]

[INFO  2015-12-13 20:56:34 StormClientHandler:56 Netty-Client-worker-1] Connection failed:/10.161.11.201:6801

java.nio.channels.ClosedChannelException

at org.jboss.netty.channel.socket.nio.AbstractNioWorker.cleanUpWriteBuffer(AbstractNioWorker.java:405)

at org.jboss.netty.channel.socket.nio.AbstractNioWorker.close(AbstractNioWorker.java:373)

at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink.eventSunk(NioClientSocketPipelineSink.java:58)

at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.handleDownstream(OneToOneEncoder.java:54)

at org.jboss.netty.channel.Channels.close(Channels.java:812)

at org.jboss.netty.channel.AbstractChannel.close(AbstractChannel.java:197)

at com.alibaba.jstorm.message.netty.NettyClient.closeChannel(NettyClient.java:339)

at com.alibaba.jstorm.message.netty.NettyClient.setChannel(NettyClient.java:392)

at com.alibaba.jstorm.message.netty.NettyClientAsync.waitChannelReady(NettyClientAsync.java:153)

at com.alibaba.jstorm.message.netty.NettyClientAsync.handleFailedChannel(NettyClientAsync.java:208)

at com.alibaba.jstorm.message.netty.NettyClientAsync.pushBatch(NettyClientAsync.java:270)

at com.alibaba.jstorm.message.netty.NettyClientAsync.send(NettyClientAsync.java:122)

at com.alibaba.jstorm.daemon.worker.BatchTupleRunable.handleOneEvent(BatchTupleRunable.java:89)

at com.alibaba.jstorm.daemon.worker.BatchTupleRunable.handleEvent(BatchTupleRunable.java:119)

at com.alibaba.jstorm.utils.DisruptorRunable.onEvent(DisruptorRunable.java:54)

at backtype.storm.utils.DisruptorQueueImpl.consumeBatchToCursor(DisruptorQueueImpl.java:179)

at backtype.storm.utils.DisruptorQueueImpl.consumeBatchWhenAvailable(DisruptorQueueImpl.java:146)

at com.alibaba.jstorm.utils.DisruptorRunable.run(DisruptorRunable.java:68)

at com.alibaba.jstorm.callback.AsyncLoopRunnable.run(AsyncLoopRunnable.java:51)

at java.lang.Thread.run(Thread.java:745)

[INFO  2015-12-13 20:56:34 StormClientHandler:82 Netty-Client-worker-1] Connection to /10.161.11.201:6801 has been closed, channel = [id: 0x0ce74b67, /10.161.11.230:50519 :> /10.161.11.201:6801]

[INFO  2015-12-13 20:56:34 NettyClient:176 Netty-Client-worker-1] Connection established, channel = :[id: 0x71abed1e, /10.161.11.230:50924 => /10.161.11.201:6801]

[INFO  2015-12-13 20:56:34 NettyClient:386 Netty-Client-worker-1] Use new channel /10.161.11.230:50924 replace old channel null

**Comment by unsleepy22** [comment]
The usual cause for this problem is that some worker is dead, and it's tcp ports are released, while other workers still try to connect the worker, resulting in the "Connection failed" problem. 
Please check that you have try...catch for all your code blocks like prepare/open/execute/nextTuple because if an exception is raised without handling, the worker itself will be crashed(and rescheduled later).

BTW., 0.9.6.3 is pretty old, try a new version. We have some pretty good features in newer versions.
