### ISSUE TITLE
在最新代码的supervisor上的启动worker总是失败

### ISSUE THREAD

**Issue by hansonzh** [alibaba/jstorm#153]
从github下载最新源码，启动supervisor后，提交topology出现如下错误：[ERROR 2015-12-14 21:52:38 c.a.j.c.AsyncLoopRunnable:118 RefreshConnections] Async loop died!!!java.util.concurrent.ConcurrentHashMap.keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView;
java.lang.NoSuchMethodError: java.util.concurrent.ConcurrentHashMap.keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView;
        at com.alibaba.jstorm.daemon.worker.RefreshConnections.run(RefreshConnections.java:219) ~[jstorm-core-2.1.0.jar:na]
        at com.alibaba.jstorm.callback.AsyncLoopRunnable.run(AsyncLoopRunnable.java:95) ~[jstorm-core-2.1.0.jar:na]
        at java.lang.Thread.run(Thread.java:724) [na:1.7.0_40]
[ERROR 2015-12-14 21:52:38 c.a.j.c.AsyncLoopThread:87 RefreshConnections] UncaughtException
java.lang.ClassCastException: java.lang.NoSuchMethodError cannot be cast to java.lang.Exception
        at com.alibaba.jstorm.callback.AsyncLoopDefaultKill.execute(AsyncLoopDefaultKill.java:33) ~[jstorm-core-2.1.0.jar:na]
        at com.alibaba.jstorm.callback.AsyncLoopRunnable.run(AsyncLoopRunnable.java:119) ~[jstorm-core-2.1.0.jar:na]
        at java.lang.Thread.run(Thread.java:724) ~[na:1.7.0_40]

**Comment by unsleepy22** [comment]
这个是1.8跟1.7的一个不兼容点，目前2.1.0还不是完全兼容1.8，2.1.1我们会fix这个问题。

**Comment by hansonzh** [comment]
是jdk兼容性问题，已解决，多谢
