### ISSUE TITLE
Kafka+Jstorm，运行TridentTopology的时候遇到一个问题

### ISSUE THREAD

**Issue by yamanko** [alibaba/jstorm#182]
Kafka+Jstorm，提交一个新写的TridentTopology，总是跑出下面的错误，找不到原因，求助
backtype.storm.topology.FailedException: Received commit for different transaction attempt
        at storm.trident.spout.TridentSpoutExecutor.execute(TridentSpoutExecutor.java:73)
	at storm.trident.topology.TridentBoltExecutor.execute(TridentBoltExecutor.java:315)

**Comment by yamanko** [comment]
自己解决了问题，主要原因是jstorm和storm在ack和nexttuple线程上的区别，设置spout.single.thread可以临时解决这个问题
