### ISSUE TITLE
jstorm-ui的pom.xml文件错误

### ISSUE THREAD

**Issue by hammertank** [alibaba/jstorm#209]
依赖项javax.servlet:servlet-api未标记为provided，导致war包在tomcat下无法正常运行。
tomcat版本8.0.22。

**Comment by unsleepy22** [comment]
@wuchong 看一下

**Comment by wuchong** [comment]
@hammertank  我用tomcat 8.0.22 试了下，有没有标记 provided 都可以正常运行。可能是其他原因。

你那无法运行是报什么错误？ 能贴以下吗

**Comment by hammertank** [comment]
错误日志在`localhost.yyyy-mm-dd.log`文件里，触发条件是启动Tomcat后访问根路径`http:\\xxx:8080`。

### JRE信息

	$ java -version
	java version "1.7.0_67"
	Java(TM) SE Runtime Environment (build 1.7.0_67-b01)
	Java HotSpot(TM) 64-Bit Server VM (build 24.65-b04, mixed mode)

### 日志

	04-Mar-2016 19:16:16.348 INFO [localhost-startStop-1] org.apache.catalina.core.ApplicationContext.log Initializing Spring FrameworkServlet 'mvc-dispatcher'
	04-Mar-2016 19:16:18.458 INFO [localhost-startStop-1] org.apache.catalina.core.ApplicationContext.log ContextListener: contextInitialized()
	04-Mar-2016 19:16:18.458 INFO [localhost-startStop-1] org.apache.catalina.core.ApplicationContext.log SessionListener: contextInitialized()
	04-Mar-2016 19:16:57.172 SEVERE [http-nio-8080-exec-1] org.apache.catalina.core.ApplicationDispatcher.invoke Servlet.service() for servlet jsp threw exception
	 org.apache.jasper.JasperException: Unable to compile class for JSP: 
	
	An error occurred at line: [76] in the generated java file: [/home/xxx/apache-tomcat-8.0.22/work/Catalina/localhost/ROOT/org/apache/jsp/WEB_002dINF/pages/clusters_jsp.java]
	The method getDispatcherType() is undefined for the type HttpServletRequest
	
	Stacktrace:
		at org.apache.jasper.compiler.DefaultErrorHandler.javacError(DefaultErrorHandler.java:102)
		at org.apache.jasper.compiler.ErrorDispatcher.javacError(ErrorDispatcher.java:198)
		at org.apache.jasper.compiler.JDTCompiler.generateClass(JDTCompiler.java:450)
		at org.apache.jasper.compiler.Compiler.compile(Compiler.java:361)
		at org.apache.jasper.compiler.Compiler.compile(Compiler.java:336)
		at org.apache.jasper.compiler.Compiler.compile(Compiler.java:323)
		at org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:585)
		at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:363)
		at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:396)
		at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:340)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
		at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:721)
		at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:466)
		at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:391)
		at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:318)
		at org.springframework.web.servlet.view.InternalResourceView.renderMergedOutputModel(InternalResourceView.java:172)
		at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:303)
		at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1228)
		at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1011)
		at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:955)
		at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:877)
		at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:966)
		at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:857)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
		at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:842)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:617)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
		at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)
		at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:668)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1521)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1478)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.lang.Thread.run(Thread.java:745)

**Comment by wuchong** [comment]
多谢详细的日志信息和环境信息，我这里重现并修复了。

你可以使用master分支自己编译一个war包，或者手动删除 webapps/jstorm-ui-2.1.1/WEB-INF/lib/servlet-api-2.5.jar 文件。
