### ISSUE TITLE
jstorm  集群可以跑 为什么ui 监控跑不起来报错了

### ISSUE THREAD

**Issue by hubuyt** [alibaba/jstorm#211]

**Comment by hubuyt** [comment]
我的jstorm 利用zookeeper搭建的集群可以跑 但是ui监控总是报错
贴一下storm.yaml
storm.zookeeper.servers:
    - "192.168.236.111"
    - "192.168.236.112"
    - "192.168.236.113"
storm.zookeeper.root: "/jstorm"
nimbus.host: "192.168.236.111"
storm.local.dir: "%JSTORM_HOME%/data"
java.library.path: "/usr/local/lib:/opt/local/lib:/usr/lib"
supervisor.slots.ports:
    - 6800
    - 6801
    - 6802
    - 6803
topology.enable.classloader: false
supervisor.enable.cgroup: false
storm.messaging.netty.transfer.async.batch: true
topology.buffer.size.limited: true
worker.memory.size: 2147483648
topology.performance.metrics: true
topology.alimonitor.metrics.post: false
报错
com.sun.faces.mgbean.ManagedBeanCreationException: Cant instantiate class: com.alibaba.jstorm.ui.model.data.MainPage.
	at com.sun.faces.mgbean.BeanBuilder.newBeanInstance(BeanBuilder.java:193)
	at com.sun.faces.mgbean.BeanBuilder.build(BeanBuilder.java:102)
	at com.sun.faces.mgbean.BeanManager.createAndPush(BeanManager.java:409)
	at com.sun.faces.mgbean.BeanManager.create(BeanManager.java:269)
	at com.sun.faces.el.ManagedBeanELResolver.resolveBean(ManagedBeanELResolver.java:244)
	at com.sun.faces.el.ManagedBeanELResolver.getValue(ManagedBeanELResolver.java:116)
	at com.sun.faces.el.DemuxCompositeELResolver._getValue(DemuxCompositeELResolver.java:176)
	at com.sun.faces.el.DemuxCompositeELResolver.getValue(DemuxCompositeELResolver.java:203)
	at org.apache.el.parser.AstIdentifier.getValue(AstIdentifier.java:71)
	at org.apache.el.parser.AstValue.getTarget(AstValue.java:94)
	at org.apache.el.parser.AstValue.getType(AstValue.java:82)
	at org.apache.el.ValueExpressionImpl.getType(ValueExpressionImpl.java:171)
	at com.sun.faces.facelets.el.TagValueExpression.getType(TagValueExpression.java:98)
	at org.primefaces.component.datatable.DataTable.isLazy(DataTable.java:968)
	at org.primefaces.component.datatable.DataTableRenderer.encodeMarkup(DataTableRenderer.java:191)
	at org.primefaces.component.datatable.DataTableRenderer.encodeEnd(DataTableRenderer.java:108)
	at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:875)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1786)
	at javax.faces.render.Renderer.encodeChildren(Renderer.java:168)
	at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:845)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1779)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1782)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1782)
	at com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:402)
	at com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:125)
	at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:121)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
	at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:139)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:594)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:436)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1078)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: Don't know how to convert null to int
	at backtype.storm.utils.NimbusClient.getConfiguredClient(NimbusClient.java:25)
	at com.alibaba.jstorm.ui.UIUtils.getNimbusClient(UIUtils.java:570)
	at com.alibaba.jstorm.ui.model.data.MainPage.init(MainPage.java:75)
	at com.alibaba.jstorm.ui.model.data.MainPage.<init>(MainPage.java:63)
	at sun.reflect.GeneratedConstructorAccessor16.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at java.lang.Class.newInstance(Class.java:379)
	at com.sun.faces.mgbean.BeanBuilder.newBeanInstance(BeanBuilder.java:188)
	... 48 more
Caused by: java.lang.IllegalArgumentException: Don't know how to convert null to int
	at backtype.storm.utils.Utils.getInt(Utils.java:372)
	at backtype.storm.utils.Utils.newCurator(Utils.java:431)
	at backtype.storm.utils.Utils.newCurator(Utils.java:401)
	at backtype.storm.security.auth.ThriftClient.getMaster(ThriftClient.java:52)
	at backtype.storm.security.auth.ThriftClient.<init>(ThriftClient.java:38)
	at backtype.storm.utils.NimbusClient.<init>(NimbusClient.java:35)
	at backtype.storm.utils.NimbusClient.<init>(NimbusClient.java:30)
	at backtype.storm.utils.NimbusClient.getConfiguredClient(NimbusClient.java:23)
	... 56 more

**Comment by wuchong** [comment]
你用的还是 0.9.x 版本的UI，跟 2.x 的jstorm是不兼容的。 你用 2.1.x 的UI就可以了。

**Comment by hubuyt** [comment]
但是我的jstorm版本和ui是一个版本啊 ui和jstorm一起下载使用的

**Comment by wuchong** [comment]
你用的是 0.9.x 版本的 jstorm ？

**Comment by hubuyt** [comment]
是的 0.9.2

**Comment by unsleepy22** [comment]
0.9.2已经是非常非常老的版本了，你可以用0.9.7么？

**Comment by hubuyt** [comment]
嗯  用了最新版本的 没事了
