### ISSUE TITLE
原生例子  TridentReach.java 异常

### ISSUE THREAD

**Issue by ranqiqiang** [alibaba/jstorm#231]
`finished:false header:: 1007,5  replyHeader:: 1007,225,0  request:: '/jstorm/taskerrors/reach-1-1459233113/last_error,#ffffffacffffffed0573720116a6176612e7574696c2e486173684d617057ffffffdaffffffc1ffffffc31660ffffffd1302460a6c6f6164466163746f7249097468726573686f6c6478703f400000007780001000173720116a6176612e6c616e672e496e746567657212ffffffe2ffffffa0ffffffa4fffffff7ffffff81ffffff8738201490576616c756578720106a6176612e6c616e672e4e756d626572ffffff86ffffffacffffff951dbffffff94ffffffe0ffffff8b20078700078740a3134353932333331383378,-1  response:: s{30,225,1459233114845,1459233183256,63,0,0,0,172,0,30} 
14:33:03.257 [EventManagerImp] ERROR c.a.j.d.supervisor.SyncProcessEvent - Failed to launchWorker workerId:9fa634c0-bac2-4580-906f-0fc7dd87724f:6905
java.lang.RuntimeException: java.lang.IllegalStateException: Attempting to call unbound fn: #'carbonite.api/register-serializers
	at backtype.storm.serialization.SerializationFactory.getKryo(SerializationFactory.java:75) ~[classes/:na]
	at backtype.storm.serialization.KryoValuesDeserializer.<init>(KryoValuesDeserializer.java:33) ~[classes/:na]
	at backtype.storm.serialization.KryoTupleDeserializer.<init>(KryoTupleDeserializer.java:52) ~[classes/:na]
	at com.alibaba.jstorm.daemon.worker.WorkerData.updateKryoSerializer(WorkerData.java:420) ~[classes/:na]
	at com.alibaba.jstorm.daemon.worker.WorkerData.<init>(WorkerData.java:376) ~[classes/:na]
	at com.alibaba.jstorm.daemon.worker.Worker.<init>(Worker.java:67) ~[classes/:na]
	at com.alibaba.jstorm.daemon.worker.Worker.mk_worker(Worker.java:248) ~[classes/:na]
	at com.alibaba.jstorm.daemon.supervisor.SyncProcessEvent.launchWorker(SyncProcessEvent.java:440) [classes/:na]
	at com.alibaba.jstorm.daemon.supervisor.SyncProcessEvent.startNewWorkers(SyncProcessEvent.java:987) [classes/:na]
	at com.alibaba.jstorm.daemon.supervisor.SyncProcessEvent.run(SyncProcessEvent.java:182) [classes/:na]
	at com.alibaba.jstorm.daemon.supervisor.SyncSupervisorEvent.run(SyncSupervisorEvent.java:191) [classes/:na]
	at com.alibaba.jstorm.event.EventManagerImp.run(EventManagerImp.java:71) [classes/:na]
	at com.alibaba.jstorm.callback.AsyncLoopRunnable.run(AsyncLoopRunnable.java:95) [classes/:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
Caused by: java.lang.IllegalStateException: Attempting to call unbound fn: #'carbonite.api/register-serializers
	at clojure.lang.Var$Unbound.throwArity(Var.java:43) ~[clojure-1.6.0.jar:na]
	at clojure.lang.AFn.invoke(AFn.java:36) ~[clojure-1.6.0.jar:na]
	at clojure.lang.Var.invoke(Var.java:383) ~[clojure-1.6.0.jar:na]
	at carbonite.JavaBridge.registerPrimitives(JavaBridge.java:43) ~[carbonite-1.4.0.jar:na]
	at backtype.storm.serialization.SerializationFactory.getKryo(SerializationFactory.java:72) ~[classes/:na]
	... 13 common frames omitted
14:33:03.257 [EventManagerImp] ERROR c.a.j.d.supervisor.SyncProcessEvent - Failed Sync Process
java.lang.RuntimeException: java.lang.IllegalStateException: Attempting to call unbound fn: #'carbonite.api/register-serializers
	at backtype.storm.serialization.SerializationFactory.getKryo(SerializationFactory.java:75) ~[classes/:na]
	at backtype.storm.serialization.KryoValuesDeserializer.<init>(KryoValuesDeserializer.java:33) ~[classes/:na]
	at backtype.storm.serialization.KryoTupleDeserializer.<init>(KryoTupleDeserializer.java:52) ~[classes/:na]
	at com.alibaba.jstorm.daemon.worker.WorkerData.updateKryoSerializer(WorkerData.java:420) ~[classes/:na]
	at com.alibaba.jstorm.daemon.worker.WorkerData.<init>(WorkerData.java:376) ~[classes/:na]
	at com.alibaba.jstorm.daemon.worker.Worker.<init>(Worker.java:67) ~[classes/:na]
	at com.alibaba.jstorm.daemon.worker.Worker.mk_worker(Worker.java:248) ~[classes/:na]
	at com.alibaba.jstorm.daemon.supervisor.SyncProcessEvent.launchWorker(SyncProcessEvent.java:440) ~[classes/:na]
	at com.alibaba.jstorm.daemon.supervisor.SyncProcessEvent.startNewWorkers(SyncProcessEvent.java:987) ~[classes/:na]
	at com.alibaba.jstorm.daemon.supervisor.SyncProcessEvent.run(SyncProcessEvent.java:182) ~[classes/:na]
	at com.alibaba.jstorm.daemon.supervisor.SyncSupervisorEvent.run(SyncSupervisorEvent.java:191) [classes/:na]
	at com.alibaba.jstorm.event.EventManagerImp.run(EventManagerImp.java:71) [classes/:na]
	at com.alibaba.jstorm.callback.AsyncLoopRunnable.run(AsyncLoopRunnable.java:95) [classes/:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
Caused by: java.lang.IllegalStateException: Attempting to call unbound fn: #'carbonite.api/register-serializers`

电脑mac：10.10
jdk：1.7
IDE：idea14
trident 里面的都报这个异常。

其他问题：我想用 stream 的join 操作，但是我通过FixedBatchSpout  创建的 2个流 批次发送，只能发一批就没了，能帮忙看看吗？
` public static class FilelterTest  extends BaseFilter {

        @Override
        public boolean isKeep(TridentTuple tuple) {
            String get =tuple.getString(2);
            if(get.startsWith("186")){
                return true;
            }
            return false;
        }
    }

    public static class FunctionTest extends BaseFunction {

        @Override
        public void execute(TridentTuple tuple, TridentCollector collector) {

            String getName = tuple.getString(0);
            String getid = tuple.getString(1);
            String getTel = tuple.getString(2);
            System.out.println("过滤后数据：============"+tuple.getValues());

            collector.emit(new Values(getName,getid,getTel));
        }

    }

    public static class FunctionTest3 extends BaseFunction {

        @Override
        public void execute(TridentTuple tuple, TridentCollector collector) {

            System.out.println(tuple.getValues());
        }

    }

        public static void main(String[] args) throws InterruptedException {

            FixedBatchSpout spout = new FixedBatchSpout(
                     new Fields("name","idName","tel"), 4,
                     new Values("Jackxx","1","186107"),
                     new Values("Tome","2","1514697"),
                     new Values("Lay","3","186745"),
                     new Values("Lucy","4","1396478"));

            FixedBatchSpout spout2 = new FixedBatchSpout(
                     new Fields("sex","idSex"), 4,
                     new Values("Boy","2"),
                     new Values("Boy","1"),
                     new Values("Gril","3"),
                     new Values("Gril","4"));
            System.out.println(2);
            //设置是否循环
            spout.setCycle(true);
            spout2.setCycle(true);
            System.out.println(1111111);
            //构建Trident的Topo
            TridentTopology topology = new TridentTopology();
            //定义过滤器： 电话号码不是 186开头的过滤
            FilelterTest ft = new FilelterTest();
            //定义方法 用来显示过滤后的数据
            FunctionTest function = new FunctionTest();
            //根据spout构建第一个Stream
            Stream st = topology.newStream("sp1", spout);
            //对第一个Stream数据显示。
//            Stream st_1 = st.each(new Fields("name","idName","tel"), function, new Fields("out_name","out_idName","out_tel"));
            //根据第二个Spout构建Stream，为了测试join用
            Stream st2 = topology.newStream("sp2", spout2);
            /**
             * 开始Join  st和st2这两个流，类比sql中join的话是：
             * st join st2 on  joinFields1 =  joinFields2
             * 需要注意的是以st为数据基础
             * topology.join(st, new Fields("idName"), st2, new Fields("idSex"), new Fields("id","name","tel","sex"))
             * 那么结果将是以spout为数据基础，结果会将上面的4个数据信息全部打出
             */
            Stream st3=	topology.join(st,
                    new Fields("idName"), st2,
                    new Fields("idSex"),
                    new Fields("Res_id","Res_name","Res_tel","Res_sex"));
            //创建一个方法，为了显示合并和过滤后的结果
            FunctionTest3 t3 =new FunctionTest3();
            st3.each(new Fields("Res_id","Res_name","Res_tel","Res_sex"), ft)
                    .each(new Fields("Res_id", "Res_name", "Res_tel", "Res_sex"), t3,
                            new Fields("out1_id", "out1_name", "ou1t_tel", "out1_sex"));

            Config cf = new Config();
            cf.setNumWorkers(1);
            cf.setNumAckers(0);
            cf.setDebug(false);

            LocalCluster lc = new LocalCluster();
            lc.submitTopology("TestTopo", cf, topology.build());

            Thread.sleep(10000*10);

            lc.shutdown();
        }`

**Comment by hustfxj** [comment]
如果你可以改的话，干脆把       try {
            JavaBridge.registerPrimitives(k);
            JavaBridge.registerCollections(k);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
去掉去，试一试

**Comment by longdafeng** [comment]
tridentreach， 我之前跑过是ok的， 你用的版本是哪个？ 发个链接给我看看

2016-03-29 20:51 GMT+08:00 John Fang <notifications@github.com>:

**Comment by anymorefree** [comment]
我也遇到了，2.2.1版本

**Comment by xiaohongxiedaima** [comment]
jstrom 天坑 升级到2.2.1 亲测可用
