### ISSUE TITLE
jstorm UI启动的错误

### ISSUE THREAD

**Issue by caiyifeng** [alibaba/jstorm#244]
我在jstorm.0.9.6.3的基础上升级了jstorm到2.1.1版本，nimbus,supervisor等都启动正常，但在启动UI的时候，却报如下错误，请问怎么解决啊：Caused by: org.apache.thrift7.protocol.TProtocolException: Required field 'supervisors' is unset! Struct:ClusterSummary(supervisors:null, nimbus_uptime_secs:0, topologies:[])
        at backtype.storm.generated.ClusterSummary.validate(ClusterSummary.java:566)
        at backtype.storm.generated.ClusterSummary.read(ClusterSummary.java:497)
        at backtype.storm.generated.Nimbus$getClusterInfo_result.read(Nimbus.java:12365)
        at org.apache.thrift7.TServiceClient.receiveBase(TServiceClient.java:78)
        at backtype.storm.generated.Nimbus$Client.recv_getClusterInfo(Nimbus.java:517)
        at backtype.storm.generated.Nimbus$Client.getClusterInfo(Nimbus.java:505)
        at com.alibaba.jstorm.ui.model.data.MainPage.init(MainPage.java:66)
        at com.alibaba.jstorm.ui.model.data.MainPage.<init>(MainPage.java:54)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
        at java.lang.Class.newInstance(Class.java:442)
        at com.sun.faces.mgbean.BeanBuilder.newBeanInstance(BeanBuilder.java:188)

**Comment by wuchong** [comment]
你这个应该是用了 0.9.x 版本的UI。 2.1.1版本的jstorm必须用 2.1.x 版本的UI， 与老UI是不兼容的。
