### ISSUE TITLE
jstorm2.1.1提交topology连接zookeeper超时

### ISSUE THREAD

**Issue by noprom** [alibaba/jstorm#278]
如题，我本地zookeeper已经打开，但是提交topology提示2181端口连接超时
1.zookeeper已经开启
`
➜  PreliminaryDemo git:(master) ✗ $ZOOKEEPER_HOME/bin/zkServer.sh status
ZooKeeper JMX enabled by default
Using config: /opt/app/zookeeper/zookeeper-3.4.8/bin/../conf/zoo.cfg
Mode: standalone
`
2.jstorm提交错误
`
/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/bin/java

Running: java -client -Xms256m -Xmx256m -Djstorm.home=/opt/app/jstorm/jstorm-2.1.1 -Dstorm.options= -Djava.library.path=/usr/local/lib:/opt/local/lib:/usr/lib -Dstorm.jar=/Users/noprom/Documents/Dev/Java/Pro/IdeaPro/PreliminaryDemo/target/preliminary.demo-1.0-SNAPSHOT.jar -Dstorm.root.logger=INFO,stdout -Dlogback.configurationFile=/opt/app/jstorm/jstorm-2.1.1/conf/client_logback.xml -Dlog4j.configuration=File:/opt/app/jstorm/jstorm-2.1.1/conf/client_log4j.properties -Dexclude.jars= -cp /Users/noprom/Documents/Dev/Java/Pro/IdeaPro/PreliminaryDemo/target/preliminary.demo-1.0-SNAPSHOT.jar:/opt/app/jstorm/jstorm-2.1.1/conf:/opt/app/jstorm/jstorm-2.1.1/bin::/opt/app/jstorm/jstorm-2.1.1/jstorm-core-2.1.1.jar:/opt/app/jstorm/jstorm-2.1.1/lib/asm-4.0.jar:/opt/app/jstorm/jstorm-2.1.1/lib/carbonite-1.4.0.jar:/opt/app/jstorm/jstorm-2.1.1/lib/chill-java-0.3.5.jar:/opt/app/jstorm/jstorm-2.1.1/lib/clojure-1.6.0.jar:/opt/app/jstorm/jstorm-2.1.1/lib/commons-cli-1.2.jar:/opt/app/jstorm/jstorm-2.1.1/lib/commons-codec-1.6.jar:/opt/app/jstorm/jstorm-2.1.1/lib/commons-exec-1.1.jar:/opt/app/jstorm/jstorm-2.1.1/lib/commons-io-2.4.jar:/opt/app/jstorm/jstorm-2.1.1/lib/commons-lang-2.5.jar:/opt/app/jstorm/jstorm-2.1.1/lib/commons-logging-1.1.3.jar:/opt/app/jstorm/jstorm-2.1.1/lib/curator-client-2.5.0.jar:/opt/app/jstorm/jstorm-2.1.1/lib/curator-framework-2.5.0.jar:/opt/app/jstorm/jstorm-2.1.1/lib/disruptor-3.3.2.jar:/opt/app/jstorm/jstorm-2.1.1/lib/gson-2.3.1.jar:/opt/app/jstorm/jstorm-2.1.1/lib/guava-16.0.1.jar:/opt/app/jstorm/jstorm-2.1.1/lib/httpclient-4.3.3.jar:/opt/app/jstorm/jstorm-2.1.1/lib/httpcore-4.3.2.jar:/opt/app/jstorm/jstorm-2.1.1/lib/jgrapht-core-0.9.0.jar:/opt/app/jstorm/jstorm-2.1.1/lib/jline-0.9.94.jar:/opt/app/jstorm/jstorm-2.1.1/lib/json-simple-1.1.jar:/opt/app/jstorm/jstorm-2.1.1/lib/kryo-2.21.jar:/opt/app/jstorm/jstorm-2.1.1/lib/libthrift-0.9.2.jar:/opt/app/jstorm/jstorm-2.1.1/lib/log4j-over-slf4j-1.6.6.jar:/opt/app/jstorm/jstorm-2.1.1/lib/logback-classic-1.0.13.jar:/opt/app/jstorm/jstorm-2.1.1/lib/logback-core-1.0.13.jar:/opt/app/jstorm/jstorm-2.1.1/lib/metrics-core-3.1.2.jar:/opt/app/jstorm/jstorm-2.1.1/lib/metrics-healthchecks-3.1.2.jar:/opt/app/jstorm/jstorm-2.1.1/lib/metrics-jvm-3.1.2.jar:/opt/app/jstorm/jstorm-2.1.1/lib/netty-3.9.0.Final.jar:/opt/app/jstorm/jstorm-2.1.1/lib/objenesis-1.2.jar:/opt/app/jstorm/jstorm-2.1.1/lib/reflectasm-1.07-shaded.jar:/opt/app/jstorm/jstorm-2.1.1/lib/rocksdbjni-3.10.1.jar:/opt/app/jstorm/jstorm-2.1.1/lib/servlet-api-2.5.jar:/opt/app/jstorm/jstorm-2.1.1/lib/slf4j-api-1.7.5.jar:/opt/app/jstorm/jstorm-2.1.1/lib/snakeyaml-1.11.jar:/opt/app/jstorm/jstorm-2.1.1/lib/zookeeper-3.4.6.jar com.alibaba.middleware.race.jstorm.RaceTopology
588  [main] INFO  com.alibaba.jstorm.utils.LoadConf - Using defaults.yaml from resources
709  [main] INFO  com.alibaba.jstorm.utils.LoadConf - Using storm.yaml from resources
765  [main] INFO  com.alibaba.jstorm.utils.LoadConf - Using defaults.yaml from resources
809  [main] INFO  com.alibaba.jstorm.utils.LoadConf - Using storm.yaml from resources
832  [main] INFO  backtype.storm.utils.StormBoundedExponentialBackoffRetry - The baseSleepTimeMs [1000] the maxSleepTimeMs [30000] the maxRetries [20]
16018 [main] ERROR org.apache.curator.ConnectionState - Connection timed out for connection string (localhost:2181/jstorm/nimbus_master) and timeout (15000) / elapsed (15096)
org.apache.curator.CuratorConnectionLossException: KeeperErrorCode = ConnectionLoss
	at org.apache.curator.ConnectionState.checkTimeouts(ConnectionState.java:198) [curator-client-2.5.0.jar:na]
	at org.apache.curator.ConnectionState.getZooKeeper(ConnectionState.java:88) [curator-client-2.5.0.jar:na]
	at org.apache.curator.CuratorZookeeperClient.getZooKeeper(CuratorZookeeperClient.java:115) [curator-client-2.5.0.jar:na]
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.getZooKeeper(CuratorFrameworkImpl.java:488) [curator-framework-2.5.0.jar:na]
	at org.apache.curator.framework.imps.ExistsBuilderImpl$2.call(ExistsBuilderImpl.java:172) [curator-framework-2.5.0.jar:na]
	at org.apache.curator.framework.imps.ExistsBuilderImpl$2.call(ExistsBuilderImpl.java:161) [curator-framework-2.5.0.jar:na]
	at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:107) [curator-client-2.5.0.jar:na]
	at org.apache.curator.framework.imps.ExistsBuilderImpl.pathInForeground(ExistsBuilderImpl.java:157) [curator-framework-2.5.0.jar:na]
	at org.apache.curator.framework.imps.ExistsBuilderImpl.forPath(ExistsBuilderImpl.java:148) [curator-framework-2.5.0.jar:na]
	at org.apache.curator.framework.imps.ExistsBuilderImpl.forPath(ExistsBuilderImpl.java:36) [curator-framework-2.5.0.jar:na]
	at backtype.storm.security.auth.ThriftClient.getMasterByZk(ThriftClient.java:102) [jstorm-core-2.1.1.jar:na]
	at backtype.storm.security.auth.ThriftClient.getMaster(ThriftClient.java:128) [jstorm-core-2.1.1.jar:na]
	at backtype.storm.security.auth.ThriftClient.<init>(ThriftClient.java:87) [jstorm-core-2.1.1.jar:na]
	at backtype.storm.utils.NimbusClient.<init>(NimbusClient.java:94) [jstorm-core-2.1.1.jar:na]
	at backtype.storm.utils.NimbusClient.getConfiguredClientAs(NimbusClient.java:76) [jstorm-core-2.1.1.jar:na]
	at backtype.storm.utils.NimbusClient.getConfiguredClient(NimbusClient.java:45) [jstorm-core-2.1.1.jar:na]
	at backtype.storm.utils.NimbusClient.getConfiguredClient(NimbusClient.java:40) [jstorm-core-2.1.1.jar:na]
	at backtype.storm.StormSubmitter.submitTopology(StormSubmitter.java:115) [jstorm-core-2.1.1.jar:na]
	at backtype.storm.StormSubmitter.submitTopology(StormSubmitter.java:59) [jstorm-core-2.1.1.jar:na]
	at com.alibaba.middleware.race.jstorm.RaceTopology.main(RaceTopology.java:43) [preliminary.demo-1.0-SNAPSHOT.jar:na]
`

**Comment by unsleepy22** [comment]
这是在mac本机上部署了集群？看下storm.yaml中zk的配置呢

**Comment by noprom** [comment]
@unsleepy22  您好，我的zk配置就是本机配置：
`
########### These MUST be filled in for a storm configuration
 storm.zookeeper.servers:
     - "localhost"

 storm.zookeeper.root: "/jstorm"

# cluster.name: "default"

 #nimbus.host/nimbus.host.start.supervisor is being used by $JSTORM_HOME/bin/start.sh
 #it only support IP, please don't set hostname
 # For example
 # nimbus.host: "10.132.168.10, 10.132.168.45"
 #nimbus.host: "localhost"
 #nimbus.host.start.supervisor: false
 
# %JSTORM_HOME% is the jstorm home directory
 storm.local.dir: "%JSTORM_HOME%/data"
 # please set absolute path, default path is JSTORM_HOME/logs
# jstorm.log.dir: "absolute path"
 
 java.library.path: "/usr/local/lib:/opt/local/lib:/usr/lib"
`

**Comment by longdafeng** [comment]
storm.zookeeper.servers:
- "localhost"


你换成ip 试试， 另外， 你用zk 客户端先连一下zk，看能不能连通
