### ISSUE TITLE
jstorm使用demo例子出现： java.lang.RuntimeException: No alive nimbus 

### ISSUE THREAD

**Issue by AcceptedBoy** [alibaba/jstorm#281]
今天，我在启动`jstorm`的`nimbus`之后，就使用了`jstorm jar demo-1.0-SNAPSHOT.jar com.alibaba.jstorm.TestTopology`。然后就报错了：
```
java.lang.RuntimeException: java.lang.RuntimeException: Failed to get master from ZK.
        at backtype.storm.utils.NimbusClient.getConfiguredClientAs(NimbusClient.java:80)
        at backtype.storm.utils.NimbusClient.getConfiguredClient(NimbusClient.java:45)
        at backtype.storm.utils.NimbusClient.getConfiguredClient(NimbusClient.java:40)
        at backtype.storm.StormSubmitter.submitTopology(StormSubmitter.java:115)
        at backtype.storm.StormSubmitter.submitTopology(StormSubmitter.java:59)
        at com.alibaba.middleware.race.jstorm.RaceTopology.main(RaceTopology.java:43)
Caused by: java.lang.RuntimeException: Failed to get master from ZK.
        at backtype.storm.security.auth.ThriftClient.getMaster(ThriftClient.java:131)
        at backtype.storm.security.auth.ThriftClient.<init>(ThriftClient.java:87)
        at backtype.storm.utils.NimbusClient.<init>(NimbusClient.java:94)
        at backtype.storm.utils.NimbusClient.getConfiguredClientAs(NimbusClient.java:76)
        ... 5 more
Caused by: java.lang.RuntimeException: No alive nimbus 
        at backtype.storm.security.auth.ThriftClient.getMasterByZk(ThriftClient.java:103)
        at backtype.storm.security.auth.ThriftClient.getMaster(ThriftClient.java:128)
        ... 8 more
```

使用了`jps -l`出现了：
```
2933 org.apache.zookeeper.server.quorum.QuorumPeerMain
3209 org.apache.catalina.startup.Bootstrap
3443 sun.tools.jps.Jps
```

使用了`ps -aux | grep nimbus`出现了：
```
root      3456  0.0  0.0 112656   968 pts/1    S+   11:24   0:00 grep --color=auto nimbus
```

有哪位大神知道是什么缘故会导致这样的结果，我要怎样解决这个问题？

**Comment by fengjian428** [comment]
nimbus启动失败了， nimbus.log的内容贴出来看看吧

**Comment by woderia** [comment]
遇到同样的问题 楼主怎么解决的？

**Comment by LXHING999** [comment]
同求！
