### ISSUE TITLE
jstorm2.1.1 Fail to run supervisor  java.lang.ClassCastException 

### ISSUE THREAD

**Issue by dongeforever** [alibaba/jstorm#290]
java.lang.ClassCastException: java.lang.String cannot be cast to java.util.List
    at com.alibaba.jstorm.cluster.DistributedClusterState.mkZk(DistributedClusterState.java:105) ~[jstorm-core-2.1.1.jar:na]
    at com.alibaba.jstorm.cluster.DistributedClusterState.<init>(DistributedClusterState.java:72) ~[jstorm-core-2. 1.1.jar:na]
    at com.alibaba.jstorm.cluster.StormZkClusterState.<init>(StormZkClusterState.java:67) ~[jstorm-core-2.1.1.jar: na]
    at com.alibaba.jstorm.cluster.Cluster.mk_storm_cluster_state(Cluster.java:140) ~[jstorm-core-2.1.1.jar:na]
    at com.alibaba.jstorm.daemon.supervisor.Supervisor.mkSupervisor(Supervisor.java:96) [jstorm-core-2.1.1.jar:na]
    at com.alibaba.jstorm.daemon.supervisor.Supervisor.run(Supervisor.java:201) [jstorm-core-2.1.1.jar:na]
    at com.alibaba.jstorm.daemon.supervisor.Supervisor.main(Supervisor.java:237) [jstorm-core-2.1.1.jar:na]
~

nimbus is running ok, but supervisor dose not work, who know why ?

**Comment by dongeforever** [comment]
I found the reason, from the conf/storm.yaml:

storm.zookeeper.servers:  "10.171.52.249" 

the correct syntax should be:

  storm.zookeeper.servers: 
    -  "10.171.52.249" 

jstorm interpret the  storm.zookeeper.servers as a list, but I wrote it as a string
