### ISSUE TITLE
DRPC运行错误，何解？？

### ISSUE THREAD

**Issue by caiyifeng** [alibaba/jstorm#300]
您好： 我运行源码中提供的drpc例子：ReachTopoogy.,
我在使用客户端查询的时候，后台报错如下：
[ERROR 2016-07-03 18:59:10 b.s.d.DRPCSpout:189 spout:10-MultipleThreadSpoutExecutors] Failed to fetch DRPC result from DRPC server
org.apache.thrift.TApplicationException: fetchRequest failed: out of sequence response
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:76) ~[libthrift-0.9.2.jar:0.9.2]
	at backtype.storm.generated.DistributedRPCInvocations$Client.recv_fetchRequest(DistributedRPCInvocations.java:120) ~[jstorm-core-2.1.1.jar:na]
	at backtype.storm.generated.DistributedRPCInvocations$Client.fetchRequest(DistributedRPCInvocations.java:107) ~[jstorm-core-2.1.1.jar:na]
	at backtype.storm.drpc.DRPCInvocationsClient.fetchRequest(DRPCInvocationsClient.java:86) ~[jstorm-core-2.1.1.jar:na]
	at backtype.storm.drpc.DRPCSpout.nextTuple(DRPCSpout.java:174) ~[jstorm-core-2.1.1.jar:na]
	at com.alibaba.jstorm.task.execute.spout.SpoutExecutors.nextTuple(SpoutExecutors.java:175) [jstorm-core-2.1.1.jar:na]
	at com.alibaba.jstorm.task.execute.spout.MultipleThreadSpoutExecutors.run(MultipleThreadSpoutExecutors.java:79) [jstorm-core-2.1.1.jar:na]
	at com.alibaba.jstorm.callback.AsyncLoopRunnable.run(AsyncLoopRunnable.java:95) [jstorm-core-2.1.1.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
[ERROR 2016-07-03 18:59:10 b.s.d.DRPCSpout:239 spout:10-AckerRunnable] Failed to fail request
org.apache.thrift.transport.TTransportException: Cannot read from null inputStream
	at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:123) ~[libthrift-0.9.2.jar:0.9.2]
	at org.apache.thrift.transport.TTransport.readAll(TTransport.java:86) ~[libthrift-0.9.2.jar:0.9.2]
	at org.apache.thrift.transport.TFramedTransport.readFrame(TFramedTransport.java:129) ~[libthrift-0.9.2.jar:0.9.2]
	at org.apache.thrift.transport.TFramedTransport.read(TFramedTransport.java:101) ~[libthrift-0.9.2.jar:0.9.2]
	at org.apache.thrift.transport.TTransport.readAll(TTransport.java:86) ~[libthrift-0.9.2.jar:0.9.2]
	at org.apache.thrift.protocol.TBinaryProtocol.readStringBody(TBinaryProtocol.java:380) ~[libthrift-0.9.2.jar:0.9.2]
	at org.apache.thrift.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:230) ~[libthrift-0.9.2.jar:0.9.2]
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:69) ~[libthrift-0.9.2.jar:0.9.2]
	at backtype.storm.generated.DistributedRPCInvocations$Client.recv_failRequest(DistributedRPCInvocations.java:146) ~[jstorm-core-2.1.1.jar:na]
	at backtype.storm.generated.DistributedRPCInvocations$Client.failRequest(DistributedRPCInvocations.java:133) ~[jstorm-core-2.1.1.jar:na]
	at backtype.storm.drpc.DRPCInvocationsClient.failRequest(DRPCInvocationsClient.java:101) ~[jstorm-core-2.1.1.jar:na]
	at backtype.storm.drpc.DRPCSpout.fail(DRPCSpout.java:235) ~[jstorm-core-2.1.1.jar:na]
	at com.alibaba.jstorm.task.execute.spout.FailSpoutMsg.run(FailSpoutMsg.java:58) [jstorm-core-2.1.1.jar:na]
	at com.alibaba.jstorm.task.execute.spout.SpoutExecutors.processTimerEvent(SpoutExecutors.java:293) [jstorm-core-2.1.1.jar:na]
	at com.alibaba.jstorm.task.execute.spout.SpoutExecutors.onEvent(SpoutExecutors.java:222) [jstorm-core-2.1.1.jar:na]
	at backtype.storm.utils.DisruptorQueueImpl.consumeBatchToCursor(DisruptorQueueImpl.java:193) [jstorm-core-2.1.1.jar:na]
	at backtype.storm.utils.DisruptorQueueImpl.consumeBatchWhenAvailable(DisruptorQueueImpl.java:161) [jstorm-core-2.1.1.jar:na]
	at backtype.storm.utils.DisruptorQueueImpl.consumeBatch(DisruptorQueueImpl.java:100) [jstorm-core-2.1.1.jar:na]
	at com.alibaba.jstorm.task.execute.spout.MultipleThreadSpoutExecutors$AckerRunnable.run(MultipleThreadSpoutExecutors.java:109) [jstorm-core-2.1.1.jar:na]
	at com.alibaba.jstorm.callback.AsyncLoopRunnable.run(AsyncLoopRunnable.java:95) [jstorm-core-2.1.1.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]

**Comment by Longda-Feng** [comment]
drpc 不推荐使用

**Comment by hdyang12** [comment]
jstorm的远程调用除了drpc还有别的方式吗？
