### ISSUE TITLE
java.lang.IllegalArgumentException: Class is not registered: 

### ISSUE THREAD

**Issue by breezyjin** [alibaba/jstorm#304]
jstorm 2.1.1 出现该错
[WARN 2016-07-12 14:45:02 c.a.j.d.w.DrainerCtrlRunable:99 DrainerBatchCtrlRunable] serialize happened errors!!!
java.lang.IllegalArgumentException: Class is not registered: backtype.storm.generated.WorkerUploadMetrics
Note: To register this class use: kryo.register(backtype.storm.generated.WorkerUploadMetrics.class);
        at com.esotericsoftware.kryo.Kryo.getRegistration(Kryo.java:442) ~[kryo-2.21.jar:na]
        at com.esotericsoftware.kryo.util.DefaultClassResolver.writeClass(DefaultClassResolver.java:79) ~[kryo-2.21.jar:na]
        at com.esotericsoftware.kryo.Kryo.writeClass(Kryo.java:472) ~[kryo-2.21.jar:na]
        at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:565) ~[kryo-2.21.jar:na]
        at com.esotericsoftware.kryo.serializers.CollectionSerializer.write(CollectionSerializer.java:75) ~[kryo-2.21.jar:na]
        at com.esotericsoftware.kryo.serializers.CollectionSerializer.write(CollectionSerializer.java:18) ~[kryo-2.21.jar:na]
        at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:486) ~[kryo-2.21.jar:na]
        at backtype.storm.serialization.KryoValuesSerializer.serializeInto(KryoValuesSerializer.java:44) ~[jstorm-core-2.1.1.jar:na]
        at backtype.storm.serialization.KryoTupleSerializer.serializeTuple(KryoTupleSerializer.java:64) ~[jstorm-core-2.1.1.jar:na]
        at backtype.storm.serialization.KryoTupleSerializer.serializeBatch(KryoTupleSerializer.java:87) ~[jstorm-core-2.1.1.jar:na]
        at com.alibaba.jstorm.daemon.worker.DrainerBatchCtrlRunable.serialize(DrainerBatchCtrlRunable.java:27) ~[jstorm-core-2.1.1.jar:na]
        at com.alibaba.jstorm.daemon.worker.DrainerCtrlRunable.handleEvent(DrainerCtrlRunable.java:97) ~[jstorm-core-2.1.1.jar:na]
        at com.alibaba.jstorm.utils.DisruptorRunable.onEvent(DisruptorRunable.java:77) [jstorm-core-2.1.1.jar:na]
        at backtype.storm.utils.DisruptorQueueImpl.consumeBatchToCursor(DisruptorQueueImpl.java:193) [jstorm-core-2.1.1.jar:na]
        at backtype.storm.utils.DisruptorQueueImpl.consumeBatchWhenAvailable(DisruptorQueueImpl.java:161) [jstorm-core-2.1.1.jar:na]
        at com.alibaba.jstorm.utils.DisruptorRunable.run(DisruptorRunable.java:93) [jstorm-core-2.1.1.jar:na]
        at com.alibaba.jstorm.callback.AsyncLoopRunnable.run(AsyncLoopRunnable.java:95) [jstorm-core-2.1.1.jar:na]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_25]

**Comment by Longda-Feng** [comment]
这个错误从来没有看到过

你重启一下你的应用，还出现了这个错误吗？
