### ISSUE TITLE
[EventManagerImp] ERROR

### ISSUE THREAD

**Issue by cavities** [alibaba/jstorm#318]
我把报错都黏贴出来了 要怎么处理 求指教
[NettyCliworker-1] INFO  com.alibaba.jstorm.message.netty.StormClientHandler - Receive channelDisconnected to /192.168.229.132:6800, channel = [id: 0xf3495b46, /192.168.229.132:43146 :> /192.168.229.132:6800]
60147 [NettyCliworker-1] INFO  com.alibaba.jstorm.message.netty.NettyClient - Use new channel null replace old channel /192.168.229.132:43146
60147 [NettyCliworker-1] INFO  com.alibaba.jstorm.message.netty.NettyClient - Successfully close old channel /192.168.229.132:43146
60147 [NettyCliworker-1] INFO  com.alibaba.jstorm.message.netty.StormClientHandler - Connection to /192.168.229.132:6800 has been closed, channel = [id: 0xf3495b46, /192.168.229.132:43146 :> /192.168.229.132:6800]
60148 [ReconnectRunnable] INFO  com.alibaba.jstorm.message.netty.NettyClient - Reconnect ... [1], /192.168.229.132:6800, sleep 100ms
60148 [ReconnectRunnable] WARN  com.alibaba.jstorm.metric.AsmMetricRegistry - duplicate metric: WH@segmentWord-1-1471026640@192.168.229.132@6800@sys@MsgDecodeTime
60152 [Thread-16] INFO  com.alibaba.jstorm.daemon.supervisor.SupervisorManger - Successfully shutdown thread:EventManagerImp
60157 [EventManagerImp] ERROR com.alibaba.jstorm.daemon.worker.WorkerReportError - Failed update 6800errors to ZK

java.lang.InterruptedException: null
	at java.lang.Object.wait(Native Method) ~[na:1.8.0_101]
	at java.lang.Object.wait(Object.java:502) ~[na:1.8.0_101]
	at org.apache.zookeeper.ClientCnxn.submitRequest(ClientCnxn.java:1342) ~[zookeeper-3.4.6.jar:3.4.6-1569965]
	at org.apache.zookeeper.ZooKeeper.create(ZooKeeper.java:781) ~[zookeeper-3.4.6.jar:3.4.6-1569965]
	at org.apache.curator.framework.imps.CreateBuilderImpl$11.call(CreateBuilderImpl.java:676) ~[curator-framework-2.5.0.jar:na]
	at org.apache.curator.framework.imps.CreateBuilderImpl$11.call(CreateBuilderImpl.java:660) ~[curator-framework-2.5.0.jar:na]
	at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:107) ~[curator-client-2.5.0.jar:na]
	at org.apache.curator.framework.imps.CreateBuilderImpl.pathInForeground(CreateBuilderImpl.java:656) ~[curator-framework-2.5.0.jar:na]
	at org.apache.curator.framework.imps.CreateBuilderImpl.protectedPathInForeground(CreateBuilderImpl.java:441) ~[curator-framework-2.5.0.jar:na]
	at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:431) ~[curator-framework-2.5.0.jar:na]
	at org.apache.curator.framework.imps.CreateBuilderImpl$3.forPath(CreateBuilderImpl.java:239) ~[curator-framework-2.5.0.jar:na]
	at org.apache.curator.framework.imps.CreateBuilderImpl$3.forPath(CreateBuilderImpl.java:193) ~[curator-framework-2.5.0.jar:na]
	at com.alibaba.jstorm.zk.Zookeeper.createNode(Zookeeper.java:98) ~[jstorm-core-2.1.1.jar:na]
	at com.alibaba.jstorm.cluster.DistributedClusterState.set_data(DistributedClusterState.java:189) ~[jstorm-core-2.1.1.jar:na]
	at com.alibaba.jstorm.cluster.StormZkClusterState.setObject(StormZkClusterState.java:182) ~[jstorm-core-2.1.1.jar:na]
	at com.alibaba.jstorm.cluster.StormZkClusterState.setLastErrInfo(StormZkClusterState.java:458) ~[jstorm-core-2.1.1.jar:na]
	at com.alibaba.jstorm.cluster.StormZkClusterState.report_task_error(StormZkClusterState.java:429) ~[jstorm-core-2.1.1.jar:na]
	at com.alibaba.jstorm.cluster.StormZkClusterState.report_task_error(StormZkClusterState.java:382) ~[jstorm-core-2.1.1.jar:na]
	at com.alibaba.jstorm.cluster.StormZkClusterState.report_task_error(StormZkClusterState.java:376) ~[jstorm-core-2.1.1.jar:na]
	at com.alibaba.jstorm.daemon.worker.WorkerReportError.report(WorkerReportError.java:33) ~[jstorm-core-2.1.1.jar:na]
	at com.alibaba.jstorm.daemon.supervisor.SyncProcessEvent.startNewWorkers(SyncProcessEvent.java:990) [jstorm-core-2.1.1.jar:na]
	at com.alibaba.jstorm.daemon.supervisor.SyncProcessEvent.run(SyncProcessEvent.java:182) [jstorm-core-2.1.1.jar:na]
	at com.alibaba.jstorm.daemon.supervisor.SyncSupervisorEvent.run(SyncSupervisorEvent.java:191) [jstorm-core-2.1.1.jar:na]
	at com.alibaba.jstorm.event.EventManagerImp.run(EventManagerImp.java:71) [jstorm-core-2.1.1.jar:na]
	at com.alibaba.jstorm.callback.AsyncLoopRunnable.run(AsyncLoopRunnable.java:95) [jstorm-core-2.1.1.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_101]
60157 [EventManagerImp] ERROR com.alibaba.jstorm.daemon.supervisor.SyncProcessEvent - Failed to launchWorker workerId:67d5364e-d5ac-404c-ba3b-c847c23fe3ea:6800
java.lang.IllegalStateException: Shutdown in progress
	at java.lang.ApplicationShutdownHooks.add(ApplicationShutdownHooks.java:66) ~[na:1.8.0_101]
	at java.lang.Runtime.addShutdownHook(Runtime.java:211) ~[na:1.8.0_101]
	at com.alibaba.jstorm.daemon.worker.WorkerShutdown.<init>(WorkerShutdown.java:83) ~[jstorm-core-2.1.1.jar:na]
	at com.alibaba.jstorm.daemon.worker.Worker.execute(Worker.java:221) ~[jstorm-core-2.1.1.jar:na]
	at com.alibaba.jstorm.daemon.worker.Worker.mk_worker(Worker.java:252) ~[jstorm-core-2.1.1.jar:na]
	at com.alibaba.jstorm.daemon.supervisor.SyncProcessEvent.launchWorker(SyncProcessEvent.java:440) [jstorm-core-2.1.1.jar:na]
	at com.alibaba.jstorm.daemon.supervisor.SyncProcessEvent.startNewWorkers(SyncProcessEvent.java:987) [jstorm-core-2.1.1.jar:na]
	at com.alibaba.jstorm.daemon.supervisor.SyncProcessEvent.run(SyncProcessEvent.java:182) [jstorm-core-2.1.1.jar:na]
	at com.alibaba.jstorm.daemon.supervisor.SyncSupervisorEvent.run(SyncSupervisorEvent.java:191) [jstorm-core-2.1.1.jar:na]
	at com.alibaba.jstorm.event.EventManagerImp.run(EventManagerImp.java:71) [jstorm-core-2.1.1.jar:na]
	at com.alibaba.jstorm.callback.AsyncLoopRunnable.run(AsyncLoopRunnable.java:95) [jstorm-core-2.1.1.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_101]
60157 [EventManagerImp] ERROR com.alibaba.jstorm.daemon.supervisor.SyncProcessEvent - Failed Sync Process
java.lang.IllegalStateException: Shutdown in progress
	at java.lang.ApplicationShutdownHooks.add(ApplicationShutdownHooks.java:66) ~[na:1.8.0_101]
	at java.lang.Runtime.addShutdownHook(Runtime.java:211) ~[na:1.8.0_101]
	at com.alibaba.jstorm.daemon.worker.WorkerShutdown.<init>(WorkerShutdown.java:83) ~[jstorm-core-2.1.1.jar:na]
	at com.alibaba.jstorm.daemon.worker.Worker.execute(Worker.java:221) ~[jstorm-core-2.1.1.jar:na]
	at com.alibaba.jstorm.daemon.worker.Worker.mk_worker(Worker.java:252) ~[jstorm-core-2.1.1.jar:na]
	at com.alibaba.jstorm.daemon.supervisor.SyncProcessEvent.launchWorker(SyncProcessEvent.java:440) ~[jstorm-core-2.1.1.jar:na]
	at com.alibaba.jstorm.daemon.supervisor.SyncProcessEvent.startNewWorkers(SyncProcessEvent.java:987) ~[jstorm-core-2.1.1.jar:na]
	at com.alibaba.jstorm.daemon.supervisor.SyncProcessEvent.run(SyncProcessEvent.java:182) ~[jstorm-core-2.1.1.jar:na]
	at com.alibaba.jstorm.daemon.supervisor.SyncSupervisorEvent.run(SyncSupervisorEvent.java:191) [jstorm-core-2.1.1.jar:na]
	at com.alibaba.jstorm.event.EventManagerImp.run(EventManagerImp.java:71) [jstorm-core-2.1.1.jar:na]
	at com.alibaba.jstorm.callback.AsyncLoopRunnable.run(AsyncLoopRunnable.java:95) [jstorm-core-2.1.1.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_101]

**Comment by unsleepy22** [comment]
这是local mode还是cluster mode？

**Comment by unsleepy22** [comment]
看起来像是zk没有连上
