### ISSUE TITLE
求助：Failed to Sync Supervisor

### ISSUE THREAD

**Issue by jyxlcd** [alibaba/jstorm#321]
我的JStorm cluster成功启动，UI中可正常显示Supervisor nodes，递交Word Count Topology成功。但所有task都一直显示starting。Task的日志文件一直未生成，supervisor的日志文件显示Failed to Sync Supervisor以及connection refused。但我supervisor和nimbus之间应该是通的，搜索了老半天，不知道从何debug起，完全没思路，求助啊。

[ERROR 2016-08-16 17:02:46 c.a.j.d.s.SyncSupervisorEvent:207 EventManagerImp] Failed to Sync Supervisor
java.lang.RuntimeException: java.lang.RuntimeException: org.apache.thrift.transport.TTransportException: java.net.ConnectException: Connection refused
	at backtype.storm.utils.NimbusClient.getConfiguredClientAs(NimbusClient.java:80) ~[jstorm-core-2.1.1.jar:na]
	at backtype.storm.utils.NimbusClient.getConfiguredClient(NimbusClient.java:45) ~[jstorm-core-2.1.1.jar:na]
	at backtype.storm.utils.Utils.downloadFromMaster(Utils.java:430) ~[jstorm-core-2.1.1.jar:na]
	at com.alibaba.jstorm.utils.JStormServerUtils.downloadCodeFromMaster(JStormServerUtils.java:55) ~[jstorm-core-2.1.1.jar:na]
	at com.alibaba.jstorm.daemon.supervisor.SyncSupervisorEvent.downloadDistributeStormCode(SyncSupervisorEvent.java:284) ~[jstorm-core-2.1.1.jar:na]
	at com.alibaba.jstorm.daemon.supervisor.SyncSupervisorEvent.downloadStormCode(SyncSupervisorEvent.java:229) ~[jstorm-core-2.1.1.jar:na]
	at com.alibaba.jstorm.daemon.supervisor.SyncSupervisorEvent.downloadTopology(SyncSupervisorEvent.java:448) ~[jstorm-core-2.1.1.jar:na]
	at com.alibaba.jstorm.daemon.supervisor.SyncSupervisorEvent.run(SyncSupervisorEvent.java:181) ~[jstorm-core-2.1.1.jar:na]
	at com.alibaba.jstorm.event.EventManagerImp.run(EventManagerImp.java:71) [jstorm-core-2.1.1.jar:na]
	at com.alibaba.jstorm.callback.AsyncLoopRunnable.run(AsyncLoopRunnable.java:95) [jstorm-core-2.1.1.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_101]

**Comment by Longda-Feng** [comment]
都提示了nimbus 连接不上

你每台机器执行 一下hostname -i 看能不能拿到一个有效的ip（不能是127.0.0.1）， 怀疑是你机器没有配置好， jstorm无法获取一个有效的ip

如果hostname -i 取的ip的是127.0.0.1 那你百度一下，如何修改设置机器ip和hostname

```
Connection refused
at backtype.storm.utils.NimbusClient.getConfiguredClientAs(NimbusClient.java:80) ~[jstorm-core-2.1.1.jar:na]
```
