### ISSUE TITLE
我在使用trident时遇到如下冲突，能否帮忙诊断一下，谢了

### ISSUE THREAD

**Issue by caiyifeng** [alibaba/jstorm#327]
我用的jstorm2.1.1 ,storm-kafka 是）0.10.0版本，发布topology的时候遇到如下错误：
java.lang.LinkageError: loader constraint violation in interface itable initialization: when resolving method "org.apache.curator.framework.imps.CuratorFrameworkImpl$2.newZooKeeper(Ljava/lang/String;ILorg/apache/zookeeper/Watcher;Z)Lorg/apache/zookeeper/ZooKeeper;" the class loader (instance of backtype/storm/utils/WorkerClassLoader) of the current class, org/apache/curator/framework/imps/CuratorFrameworkImpl$2, and the class loader (instance of sun/misc/Launcher$AppClassLoader) for interface org/apache/curator/utils/ZookeeperFactory have different Class objects for the type org/apache/zookeeper/Watcher used in the signature
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.makeZookeeperFactory(CuratorFrameworkImpl.java:169) ~[curator-framework-2.5.0.jar:na]
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.<init>(CuratorFrameworkImpl.java:112) ~[curator-framework-2.5.0.jar:na]
	at org.apache.curator.framework.CuratorFrameworkFactory$Builder.build(CuratorFrameworkFactory.java:122) ~[curator-framework-2.5.0.jar:na]
	at org.apache.curator.framework.CuratorFrameworkFactory.newClient(CuratorFrameworkFactory.java:91) ~[curator-framework-2.5.0.jar:na]
	at storm.kafka.DynamicBrokersReader.<init>(DynamicBrokersReader.java:57) ~[stormjar.jar:na]
	at storm.kafka.trident.ZkBrokerReader.<init>(ZkBrokerReader.java:41) ~[stormjar.jar:na]
	at storm.kafka.KafkaUtils.makeBrokerReader(KafkaUtils.java:57) ~[stormjar.jar:na]
	at storm.kafka.trident.Coordinator.<init>(Coordinator.java:33) ~[stormjar.jar:na]
	at storm.kafka.trident.TransactionalTridentKafkaSpout.getCoordinator(TransactionalTridentKafkaSpout.java:41) ~[stormjar.jar:na]
	at storm.trident.spout.PartitionedTridentSpoutExecutor$Coordinator.<init>(PartitionedTridentSpoutExecutor.java:46) ~[jstorm-core-2.1.1.jar:na]
	at storm.trident.spout.PartitionedTridentSpoutExecutor.getCoordinator(PartitionedTridentSpoutExecutor.java:149) ~[jstorm-core-2.1.1.jar:na]
	at storm.trident.topology.MasterBatchCoordinator.open(MasterBatchCoordinator.java:113) ~[jstorm-core-2.1.1.jar:na]
	at com.alibaba.jstorm.task.execute.spout.SpoutExecutors.init(SpoutExecutors.java:142) ~[jstorm-core-2.1.1.jar:na]
	at com.alibaba.jstorm.task.execute.spout.MultipleThreadSpoutExecutors.init(MultipleThreadSpoutExecutors.java:64) [jstorm-core-2.1.1.jar:na]
	at com.alibaba.jstorm.task.execute.BaseExecutors.initWrapper(BaseExecutors.java:154) ~[jstorm-core-2.1.1.jar:na]
	at com.alibaba.jstorm.task.execute.spout.MultipleThreadSpoutExecutors.run(MultipleThreadSpoutExecutors.java:76) [jstorm-core-2.1.1.jar:na]
	at com.alibaba.jstorm.callback.AsyncLoopRunnable.run(AsyncLoopRunnable.java:95) [jstorm-core-2.1.1.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]

**Comment by Longda-Feng** [comment]
原因是， 你应用依赖的zookeeper 版本和jstorm依赖的zookeeper 版本发生冲突，导致无法加载zookeeper的类

最简单解决办法（如果搞不定， 我再告诉你其他方式）： 
让你应用zookeeper 版本升级到jstorm依赖的zookeeper版本

**Comment by caiyifeng** [comment]
@Longda-Feng  多谢，我后来把所有相关的zookeeper都在pom.xml中exclusion，然后又单独加了跟jstorm依赖的zookeeper的版本

**Comment by Longda-Feng** [comment]
应该ok了吧？？  @caiyifeng

**Comment by caiyifeng** [comment]
ok了，多谢了
