### ISSUE TITLE
bolt execute error,OutOfMemoryError 堆栈递归打印报错

### ISSUE THREAD

**Issue by penuel-leo** [alibaba/jstorm#344]
启动Worker后，一处理数据会出现:
`
2016-09-12 04:20:48,104 ERROR (BoltExecutors.java:191) - bolt execute error 
2016-09-12 04:20:58,591 ERROR (BoltExecutors.java:142) - MultiActionBolt:1 bolt exeutor  error
java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOf(Arrays.java:2367)
        at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:130)
        at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:114)
        at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:415)
        at java.lang.StringBuffer.append(StringBuffer.java:237)
        at java.io.StringWriter.write(StringWriter.java:112)
        at java.io.PrintWriter.write(PrintWriter.java:456)
        at java.io.PrintWriter.write(PrintWriter.java:473)
        at java.io.PrintWriter.print(PrintWriter.java:603)
        at java.io.PrintWriter.println(PrintWriter.java:756)
        at java.lang.Throwable$WrappedPrintWriter.println(Throwable.java:764)
        at java.lang.Throwable.printEnclosedStackTrace(Throwable.java:697)
        at java.lang.Throwable.printEnclosedStackTrace(Throwable.java:709)
        at java.lang.Throwable.printEnclosedStackTrace(Throwable.java:709)
        at java.lang.Throwable.printEnclosedStackTrace(Throwable.java:709)
        at java.lang.Throwable.printEnclosedStackTrace(Throwable.java:709)
        at java.lang.Throwable.printEnclosedStackTrace(Throwable.java:709)
        at java.lang.Throwable.printEnclosedStackTrace(Throwable.java:709)
        at java.lang.Throwable.printEnclosedStackTrace(Throwable.java:709)
        at java.lang.Throwable.printEnclosedStackTrace(Throwable.java:709)
        at java.lang.Throwable.printEnclosedStackTrace(Throwable.java:709)
        at java.lang.Throwable.printEnclosedStackTrace(Throwable.java:709)
        at java.lang.Throwable.printEnclosedStackTrace(Throwable.java:709)
        at java.lang.Throwable.printEnclosedStackTrace(Throwable.java:709)
        at java.lang.Throwable.printEnclosedStackTrace(Throwable.java:709)
        at java.lang.Throwable.printEnclosedStackTrace(Throwable.java:709)
        at java.lang.Throwable.printEnclosedStackTrace(Throwable.java:709)
        at java.lang.Throwable.printEnclosedStackTrace(Throwable.java:709)
        at java.lang.Throwable.printEnclosedStackTrace(Throwable.java:709)
        at java.lang.Throwable.printEnclosedStackTrace(Throwable.java:709)
        at java.lang.Throwable.printEnclosedStackTrace(Throwable.java:709)
        at java.lang.Throwable.printEnclosedStackTrace(Throwable.java:709)
`

怀疑是bug导致,循环打印java.lang.Throwable.printEnclosedStackTrace，导致栈太深，内存溢出；
增大堆栈，并且增大Permsize1G，但是一处理数据还是同样的错误；
上面是打印出来的全部堆栈，很难定位到具体是哪个代码的问题.

上面报错的line191,看了下源码，`LOG.error("bolt execute error ", e);` 这里也打印了e，但是log里就是没有，很奇怪。
line142 堆栈打印的也没走到jstorm的代码里

**Comment by hustfxj** [comment]
你看下你程序，应该是你程序的问题

**Comment by Longda-Feng** [comment]
outofmemory  出现后，很多行为就是完全不确定性的。

你关键是要看core dump， 看有没有出现内存泄漏
