### ISSUE TITLE
jstorm启动worker后cpu占用高

### ISSUE THREAD

**Issue by liyun919** [alibaba/jstorm#349]
jstorm2.1.0，同样的几台机器和环境下和代码，启动worker后，有一台机器的cpu利用率始终在50%左右很高，使用自带sample sequence-split-merge也一样。
通过jstack抓取到占用率高的线程为
"client-schedule-service-3" prio=10 tid=0x00007fbcb8415800 nid=0x1db41 waiting on condition [0x00007fbcb74f3000]
java.lang.Thread.State: WAITING (parking)
at sun.misc.Unsafe.park(Native Method)
- parking to wait for <0x000000075aacb9e8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
at java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2043)
at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1085)
at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:807)
at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1068)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
at java.lang.Thread.run(Thread.java:745)

看了源码后，将NettyClientAsync类中 scheduler.scheduleAtFixedRate(flusher, initialDelay, flushCheckInterval, TimeUnit.MILLISECONDS);这句话注释掉，cpu降低为正常范围内了，确定为这里导致的
但是不明白为什么别的机器都正常，而这句话也不可能就这样注释掉了，请问大神们这个可能由什么问题导致的

**Comment by hustfxj** [comment]
你看一下 这个worker和其它worker有什么特别，是不是网络流量比较多

**Comment by liyun919** [comment]
我们目前已经把这台机器剥离集群独立部署进行测试的，worker的话用jstorm的自带的sample（sequence-split-merge），或者自己的程序没有产生消息给spout接受，这样应该不会有什么太多的网络流量吧

**Comment by liyun919** [comment]
问题解决了，发现该机器的cpu时钟模式tsc启动加载失败，默认成了hpet模式，由于hpet的效率低于tsc模式，从而导致上述定时器代码占用大量cpu。tsc加载失败是由于主板硬件故障导致的，更换主板后问题解决！
