### ISSUE TITLE
jstorm-2.1.1 与 hbase-client-1.1.2 集成异常(原因在日志初始化, 希望由 jstorm-2.1.1 修补)

### ISSUE THREAD

**Issue by XiaoChangyu** [alibaba/jstorm#355]
jstorm-2.1.1 的 maven-javadoc-plugin 间接引入的作用域为runtime的 jcl-over-slf4j 版本过低(1.5.6). 里面调用的是 slf4j-api-1.6.x 前的版本的 org.slf4j.spi.LocationAwareLogger. 当中的方法如下:
```
public void info(Object message)
  {
    this.logger.log(null, FQCN, 20, String.valueOf(message), null);
  }
  public void info(Object message, Throwable t)
  {
    this.logger.log(null, FQCN, 20, String.valueOf(message), t);
  }
  public void warn(Object message)
  {
    this.logger.log(null, FQCN, 30, String.valueOf(message), null);
  }
  public void warn(Object message, Throwable t)
  {
    this.logger.log(null, FQCN, 30, String.valueOf(message), t);
  }
```

可以看到调用的是 `org.slf4j.spi.LocationAwareLogger.log(Marker paramMarker, String paramString1, int paramInt, String paramString2, Throwable paramThrowable);`

其方法参数表为: Marker,String,int,String,Throwable.

而 jstorm-2.1.1 其他地方引入的 slf4j-api 又是 1.6.x 以上的版本(好像发不了图, 可以从 eclipse pom.xml 的 Dependency Hierarchy 查看)
1.6.x 以后版本的 org.slf4j.spi.LocationAwareLogger 里的方法是`log(Marker paramMarker, String paramString1, int paramInt, String paramString2, Object[] paramArrayOfObject, Throwable paramThrowable);`
方法参数表: Marker,String,int,String, Object[],Throwable.

这样就冲突了. 在 runtime 时, jcl-over-slf4j 会被加入到classpath 中, 而恰巧 hbase-client-1.1.2 不知怎的(还没仔细去弄明白) 会通过 jcl-over-slf4j 来打印日志, 这时因为运行环境只有高于1.6.x版本的 slf4j-api, 而高于 1.6.x 的版本是没有参数表为 Marker,String,int,String,Throwable 的org.slf4j.spi.LocationAwareLogger.log 方法的, 于是就会抛出找不到方法的异常:
`java.lang.NoSuchMethodError: org.slf4j.spi.LocationAwareLogger.log(Lorg/slf4j/Marker;Ljava/lang/String;ILjava/lang/String;Ljava/lang/Throwable;)V
	at org.apache.commons.logging.impl.SLF4JLocationAwareLog.debug(SLF4JLocationAwareLog.java:120)
	at org.apache.hadoop.metrics2.impl.MetricsSystemImpl.register(MetricsSystemImpl.java:221)
	at org.apache.hadoop.metrics2.MetricsSystem.register(MetricsSystem.java:54)
	at org.apache.hadoop.security.UserGroupInformation$UgiMetrics.create(UserGroupInformation.java:108)
	at org.apache.hadoop.security.UserGroupInformation.<clinit>(UserGroupInformation.java:210)
	at org.apache.hadoop.hbase.security.User$SecureHadoopUser.<init>(User.java:286)
	at org.apache.hadoop.hbase.security.User$SecureHadoopUser.<init>(User.java:282)
	at org.apache.hadoop.hbase.security.User.getCurrent(User.java:185)
	at org.apache.hadoop.hbase.security.UserProvider.getCurrent(UserProvider.java:88)
	at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:215)
	at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:119)
	at p.ka.test.test_jstorm.dao.hbase.HBaseConnectionManager.init(HBaseConnectionManager.java:72)
	at p.ka.test.test_jstorm.TestBolt.prepare(TestBolt.java:45)
	at backtype.storm.topology.BasicBoltExecutor.prepare(BasicBoltExecutor.java:42)
	at com.alibaba.jstorm.task.execute.BoltExecutors.init(BoltExecutors.java:118)
	at com.alibaba.jstorm.task.execute.BaseExecutors.initWrapper(BaseExecutors.java:154)
	at com.alibaba.jstorm.task.execute.BoltExecutors.run(BoltExecutors.java:131)
	at com.alibaba.jstorm.callback.AsyncLoopRunnable.run(AsyncLoopRunnable.java:95)
	at java.lang.Thread.run(Thread.java:745)`

解决的办法有两种:
1, 主动引入高版本的 jcl-over-slf4j.
或
2, 排除掉 jstorm-2.1.1 里的 jcl-over-slf4j.

说明一下: 这个问题无法从只更改 slf4j-api 的版本来解决, 因为若将 slf4j-api 的版本改到 1.6.x 以下, 则会抛出非法访问的异常:
```
Exception in thread "main" java.lang.IllegalAccessError: tried to access field org.slf4j.impl.StaticLoggerBinder.SINGLETON from class org.slf4j.LoggerFactory
	at org.slf4j.LoggerFactory.<clinit>(LoggerFactory.java:60)
	at p.ka.test.test_jstorm.TestSpout.<clinit>(TestSpout.java:19)
	at p.ka.test.test_jstorm.TestCommitTopology.main(TestCommitTopology.java:28)
```
另外, 应该不会有人把 slf4j-api 版本改到 1.6.x 以下吧, 毕竟低版本对日志打印没有高版本的友好.

可以的话. 希望 jstorm-2.1.1 版本自己在引入 maven-javadoc-plugin 的时候主动排除掉  jcl-over-slf4j.
 主要是 jcl-over-slf4j 这玩意不是那么容易发现, 而且这本来是 jstorm-2.1.1 本身引入的自相矛盾的冲突, 所以希望能够在 jstorm-2.1.1 里面解决, 而不是留给开发者来留意这个事情.
jstorm-2.1.1 自己要改其实也很简单, 就是在 pom 引入 maven-javadoc-plugin 的时候加个排除. 或者主动引入高版本的 jcl-over-slf4j.

**Comment by hustfxj** [comment]
欢迎提交PR，我们帮你Merge进去。那么你就是jstorm的contributor啦

**Comment by XiaoChangyu** [comment]
就增加个 exclusion, 大大你确定么 (^o^)v

**Comment by XiaoChangyu** [comment]
我发现最新的 master 里这个问题已经被修复了. 而且8月份有别的人提交了去掉 eclipse 等关联的 PR. 其中就包括这个问题. 所以, 这个问题已经在还没出的新版本里解决啦.哈哈
