### ISSUE TITLE
supervisor有进程,jar包分布式提交的时候报任务无法分配,due to no alive supervisor

### ISSUE THREAD

**Issue by VincentZengli** [alibaba/jstorm#373]
jstorm 3节点环境，1个nimbus/2个supervisor，采用后台命令启动后，ps -ef |grep jstorm 均由进程，登录web-ui也可以看到nimbus和supervisor的机器，但是将jar包上传到nimbus后，进行提交，却报如下错误：
[INFO  2016-10-30 19:29:26 ConnectionStateManager:194 main-EventThread] State change: CONNECTED
[INFO  2016-10-30 19:29:27 ThriftClient:108 main] masterHost:192.168.0.13:8627
[INFO  2016-10-30 19:29:28 StormBoundedExponentialBackoffRetry:44 main] The baseSleepTimeMs [2000] the maxSleepTimeMs [60000] the maxRetries [5]
[INFO  2016-10-30 19:29:28 StormSubmitter:202 main] Jar not uploaded to master yet. Submitting jar...
[INFO  2016-10-30 19:29:28 StormSubmitter:244 main] Uploading topology jar bas_storm.jar to assigned location: /home/elsapp/deploy/data/jstorm/nimbus/inbox/d25c4279-1527-44f6-9b66-9ed5d6757132/stormjar-d25c4279-1527-44f6-9b66-9ed5d6757132.jar
[INFO  2016-10-30 19:29:36 StormSubmitter:259 main] Successfully uploaded topology jar to assigned location: /home/elsapp/deploy/data/jstorm/nimbus/inbox/d25c4279-1527-44f6-9b66-9ed5d6757132/stormjar-d25c4279-1527-44f6-9b66-9ed5d6757132.jar
[INFO  2016-10-30 19:29:36 StormSubmitter:122 main] Submitting topology bas_app_luanch in distributed mode with conf {"user.password":null,"exclude.jars":"","user.name":null,"user.group":null}
[WARN  2016-10-30 19:29:39 StormSubmitter:141 main] Failed to assign Fail to sumbit topology, Root cause:Failed to make assignment bas_app_luanch-7-1477826976, due to no alive supervisor

topologyId:bas_app_luanch-7-1477826976, uploadedJarLocation:/home/elsapp/deploy/data/jstorm/nimbus/inbox/d25c4279-1527-44f6-9b66-9ed5d6757132

TopologyAssignException(msg:Fail to sumbit topology, Root cause:Failed to make assignment bas_app_luanch-7-1477826976, due to no alive supervisor

topologyId:bas_app_luanch-7-1477826976, uploadedJarLocation:/home/elsapp/deploy/data/jstorm/nimbus/inbox/d25c4279-1527-44f6-9b66-9ed5d6757132
)
        at backtype.storm.generated.Nimbus$submitTopology_result$submitTopology_resultStandardScheme.read(Nimbus.java:6732)
        at backtype.storm.generated.Nimbus$submitTopology_result$submitTopology_resultStandardScheme.read(Nimbus.java:6700)
        at backtype.storm.generated.Nimbus$submitTopology_result.read(Nimbus.java:6634)
        at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:78)
        at backtype.storm.generated.Nimbus$Client.recv_submitTopology(Nimbus.java:243)
        at backtype.storm.generated.Nimbus$Client.submitTopology(Nimbus.java:227)
        at backtype.storm.StormSubmitter.submitTopology(StormSubmitter.java:127)
        at backtype.storm.StormSubmitter.submitTopology(StormSubmitter.java:59)
        at com.ect.bas.storm.main.BasAppLaunchMain.main(BasAppLaunchMain.java:56)
Exception in thread "main" java.lang.RuntimeException: TopologyAssignException(msg:Fail to sumbit topology, Root cause:Failed to make assignment bas_app_luanch-7-1477826976, due to no alive supervisor

每台机都配有etc/hosts,独立的机器名称和ip，请问那些问题可能导致如上问题。

**Comment by VincentZengli** [comment]
已解决，问题原因为supervisor节点的虚拟机时间和nimbus节点的虚拟机时间相差了9个小时，导致nimbus任务superviosr已经挂掉了~~~~系统时间同步后没启动正常！
