### ISSUE TITLE
启动wor

### ISSUE THREAD

**Issue by luoqingping1234** [alibaba/jstorm#374]
java.lang.RuntimeException: java.lang.ClassNotFoundException: com.alipay.dw.jstorm.example.trident.TridentWordCount$Split
	at backtype.storm.utils.Utils.javaDeserializeWithCL(Utils.java:182) ~[classes/:na]
	at backtype.storm.utils.Utils.getSetComponentObject(Utils.java:402) ~[classes/:na]
	at com.alibaba.jstorm.cluster.Common.get_task_object(Common.java:672) ~[classes/:na]
	at com.alibaba.jstorm.task.Task.<init>(Task.java:132) ~[classes/:na]
	at com.alibaba.jstorm.daemon.worker.Worker.createTasks(Worker.java:118) ~[classes/:na]
	at com.alibaba.jstorm.daemon.worker.Worker.execute(Worker.java:217) ~[classes/:na]
	at com.alibaba.jstorm.daemon.worker.Worker.mk_worker(Worker.java:252) ~[classes/:na]
	at com.alibaba.jstorm.daemon.worker.Worker.main(Worker.java:450) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_79]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_79]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_79]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_79]
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140) [idea_rt.jar:na]
Caused by: java.lang.ClassNotFoundException: com.alipay.dw.jstorm.example.trident.TridentWordCount$Split
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366) ~[na:1.7.0_79]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[na:1.7.0_79]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.7.0_79]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[na:1.7.0_79]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[na:1.7.0_79]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308) ~[na:1.7.0_79]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[na:1.7.0_79]
	at java.lang.Class.forName0(Native Method) ~[na:1.7.0_79]
	at java.lang.Class.forName(Class.java:274) ~[na:1.7.0_79]
	at java.io.ObjectInputStream.resolveClass(ObjectInputStream.java:625) ~[na:1.7.0_79]
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1612) ~[na:1.7.0_79]
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1517) ~[na:1.7.0_79]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1771) ~[na:1.7.0_79]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350) ~[na:1.7.0_79]
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1990) ~[na:1.7.0_79]
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1915) ~[na:1.7.0_79]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798) ~[na:1.7.0_79]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350) ~[na:1.7.0_79]
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1990) ~[na:1.7.0_79]
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1915) ~[na:1.7.0_79]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798) ~[na:1.7.0_79]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350) ~[na:1.7.0_79]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370) ~[na:1.7.0_79]
	at java.util.HashMap.readObject(HashMap.java:1179) ~[na:1.7.0_79]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_79]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_79]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_79]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_79]
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1017) ~[na:1.7.0_79]
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1893) ~[na:1.7.0_79]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798) ~[na:1.7.0_79]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350) ~[na:1.7.0_79]
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1990) ~[na:1.7.0_79]
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1915) ~[na:1.7.0_79]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798) ~[na:1.7.0_79]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350) ~[na:1.7.0_79]
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1990) ~[na:1.7.0_79]
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1915) ~[na:1.7.0_79]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798) ~[na:1.7.0_79]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350) ~[na:1.7.0_79]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370) ~[na:1.7.0_79]
	at backtype.storm.utils.Utils.javaDeserializeWithCL(Utils.java:175) ~[classes/:na]
	... 12 common frames omitted

启动wor报错  不知到是哪里出了问题？？

**Comment by unsleepy22** [comment]
这是本地运行还是提交到集群的？
