### ISSUE TITLE
怀疑遇到一个死锁的bug.

### ISSUE THREAD

**Issue by yunfan123** [alibaba/jstorm#377]
我的job大概是这样，两个spout 从kafka里面读数据，发给下层的bolt。
我用的是ShellBolt和ShellSpout，运行一段时间某些worker hang死了。
看jstack，SpoutExecutor都阻塞在DisruptorQueueImpl.publishDirect里面 MultiProducerSequencer.next(MultiProducerSequencer.java:128)  里面的while true 循环，其他线程（boltExecutor、TransferRunnable、Boltdeserializer等）都卡在consumeBatchWhenAvailable
(DisruptorQueueImpl.java:157) 。感觉像是spout想将消息不经过网络IO 直接通过 DisruptorQueueImpl 发给bolt，但是发不出去。然后bolt想要从DisruptorQueueImpl中消费消息又消费不了。

详细的调用栈：
用Jstack看：
bolt的jstack都如下：
BoltExecutor：
> "calc_mapping_stat:37-BoltExecutors" #65 prio=10 os_prio=0 tid=0x00007faa50003800 nid=0x2a6e5 runnable [0x00007faac9136000] java.lang.Thread.State: TIMED_WAITING (parking) at sun.misc.Unsafe.park(Native Method) - parking to wait for <0x0000000700442fe0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject) at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215) at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078) at com.lmax.disruptor.TimeoutBlockingWaitStrategy.waitFor(TimeoutBlockingWaitStrategy.java:37) at com.lmax.disruptor.ProcessingSequenceBarrier.waitFor(ProcessingSequenceBarrier.java:55) at backtype.storm.utils.DisruptorQueueImpl.consumeBatchWhenAvailable(DisruptorQueueImpl.java:157) at com.alibaba.jstorm.task.execute.BoltExecutors.run(BoltExecutors.java:137) at com.alibaba.jstorm.callback.AsyncLoopRunnable.run(AsyncLoopRunnable.java:95) at java.lang.Thread.run(Thread.java:745)

Bolt TransferRunnable:

> "calc_mapping_stat:197-TransferRunnable" #70 prio=5 os_prio=0 tid=0x00007faa3c002000 nid=0x2a72d runnable [0x00007faac8d32000] java.lang.Thread.State: TIMED_WAITING (parking) at sun.misc.Unsafe.park(Native Method) - parking to wait for <0x00000007003ff3c0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject) at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215) at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078) at com.lmax.disruptor.TimeoutBlockingWaitStrategy.waitFor(TimeoutBlockingWaitStrategy.java:37) at com.lmax.disruptor.ProcessingSequenceBarrier.waitFor(ProcessingSequenceBarrier.java:55) at backtype.storm.utils.DisruptorQueueImpl.consumeBatchWhenAvailable(DisruptorQueueImpl.java:157) at com.alibaba.jstorm.task.TaskTransfer$TransferRunnable.run(TaskTransfer.java:201) at com.alibaba.jstorm.callback.AsyncLoopRunnable.run(AsyncLoopRunnable.java:95) at java.lang.Thread.run(Thread.java:745)

Spout的 executor jstack都如下：

> "jstorm_helloworld_log_p26:320-SingleThreadSpoutExecutors" #56 prio=10 os_prio=0 tid=0x00007faa6800c800 nid=0x2a680 sleeping[0x00007fab2071e000] java.lang.Thread.State: TIMED_WAITING (sleeping) at java.lang.Thread.sleep(Native Method) at backtype.storm.utils.disruptor.MultiProducerSequencer.next(MultiProducerSequencer.java:128) at backtype.storm.utils.disruptor.MultiProducerSequencer.next(MultiProducerSequencer.java:100) at backtype.storm.utils.disruptor.RingBuffer.next(RingBuffer.java:206) at backtype.storm.utils.DisruptorQueueImpl.publishDirect(DisruptorQueueImpl.java:245) at backtype.storm.utils.DisruptorQueueImpl.publish(DisruptorQueueImpl.java:238) at backtype.storm.utils.DisruptorQueueImpl.publish(DisruptorQueueImpl.java:211) at com.alibaba.jstorm.task.TaskBatchTransfer.transfer(TaskBatchTransfer.java:107) at com.alibaba.jstorm.task.execute.spout.SpoutBatchCollector.sendBatch(SpoutBatchCollector.java:123) at com.alibaba.jstorm.task.execute.spout.SpoutBatchCollector.sendBatch(SpoutBatchCollector.java:135) at com.alibaba.jstorm.task.execute.spout.SpoutBatchCollector.sendSpoutMsg(SpoutBatchCollector.java:86) at com.alibaba.jstorm.task.execute.spout.SpoutCollector.emit(SpoutCollector.java:112) at backtype.storm.spout.SpoutOutputCollector.emit(SpoutOutputCollector.java:81) at backtype.storm.spout.ShellSpout.querySubprocess(ShellSpout.java:167) at backtype.storm.spout.ShellSpout.nextTuple(ShellSpout.java:93) at com.alibaba.jstorm.task.execute.spout.SpoutExecutors.nextTuple(SpoutExecutors.java:175) at com.alibaba.jstorm.task.execute.spout.SingleThreadSpoutExecutors.run(SingleThreadSpoutExecutors.java:76) at com.alibaba.jstorm.callback.AsyncLoopRunnable.run(AsyncLoopRunnable.java:95) at java.lang.Thread.run(Thread.java:745) 

> "client-schedule-service-3" #48 prio=5 os_prio=0 tid=0x00007faa94010000 nid=0x2a631 waiting on condition [0x00007fab21027000] java.lang.Thread.State: WAITING (parking) at sun.misc.Unsafe.park(Native Method) - parking to wait for <0x00000007007e74a0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject) at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175) at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039) at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1088) at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809) at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) at java.lang.Thread.run(Thread.java:745)

**Comment by Longda-Feng** [comment]
你的逻辑是不是这个样子

spout.nexttuple ---> bolt --> acker --> spout.ack/fail 

当fail时， 你是不是在fail里面直接emit 出去

假设，当你bolt处理慢了， 
bolt 堆积， 触发 spout.nexttuple 堆积， 同时 spout.ack/fail 堆积， 然后触发acker 堆积， acker堆积后， bolt 就再也发不出去了。

如果是这个样子，
只需要在 spout.fail 里面把失败的数据放到一个队列里面（这个动作需要非组塞方式放入）

**Comment by Longda-Feng** [comment]
每一层到下一层发送数据，都会有一层cache， 只有把所有的cache打穿，并且你spout.fail 使用不当时，才会出现死锁

**Comment by yunfan123** [comment]
@Longda-Feng 
fail的消息其实直接被我扔掉了，其他逻辑如您所说，我的应用其实不需要重试，但是我需要知道ack和fail的数量，还有就是我配置里面没有开启jstorm的backpressure。
这样来说的话，如果bolt堆积，触发spout.nexttuple堆积，及时spout.fail处理正确，spout.ack 也可能堆积呀？
这样来说的话，只要同时堆积了？就会触发jstorm死锁的bug么？
“acker堆积后，bolt就再也发不出去” 这个是指的bolt 的 ack就发不出去了么？
理解不对的地方请您指出哈。

**Comment by yunfan123** [comment]
不知道我的理解对不对，还有就是我用的配置是spout.single.thread 为 True，不过这个从栈中也能看到。
这个时候jstorm spout 的ack和executor在同样一个线程。

假设在数据量很大的情况下，我的bolt处理不过来，这时候假设所有的cache都被打满。
因为cache满，spout.nexttuple 发送阻塞，而ack和它在一个线程，这时候造成无法处理ack数据。
因为cache满，这时候bolt等待ack发送，但是由于ack发送给spout，spout又hang在emit数据。
这样造成的死锁？

**Comment by unsleepy22** [comment]
你上面这种情况下，就要等bolt慢慢处理了，这样spout就能够往下发了。

**Comment by yunfan123** [comment]
@unsleepy22 ，按我的理解，这种情况应该是完全死锁了，bolt处理完之后需要扔给acker，但是这时候acker是满了的，扔不进去，就hang了。

**Comment by luoyueshi** [comment]
这个我们好像也碰见过，一直没解决。。

**Comment by yunfan123** [comment]
@luoyueshi 
1、不要用spout.single.thread: true这个配置。
2、spout 里面fail或者ack不要emit消息，只在nextTuple里面emit.

**Comment by lizhiqiang123321** [comment]
请问，这个问题最终该怎么解决呢
