### ISSUE TITLE
好像是一个小bug

### ISSUE THREAD

**Issue by Fengdada** [alibaba/jstorm#399]

**Comment by Fengdada** [comment]
nimbus部署在Docker上，kill重启Docker时，报错（因为jstorm重启时创建的进程目录已存在）：
java.lang.RuntimeException: Failed to touch /home/jstorm/data/nimbus/pids/72                                                                                                                     
        at com.alibaba.jstorm.utils.PathUtils.touch(PathUtils.java:116) ~[jstorm-core-2.1.1.jar:na]                                                                                              
        at com.alibaba.jstorm.utils.JStormServerUtils.createPid(JStormServerUtils.java:94) ~[jstorm-core-2.1.1.jar:na]                                                                           
        at com.alibaba.jstorm.daemon.nimbus.NimbusServer.createPid(NimbusServer.java:102) [jstorm-core-2.1.1.jar:na]                                                                             
        at com.alibaba.jstorm.daemon.nimbus.NimbusServer.launchServer(NimbusServer.java:113) [jstorm-core-2.1.1.jar:na]                                                                          
        at com.alibaba.jstorm.daemon.nimbus.NimbusServer.main(NimbusServer.java:95) [jstorm-core-2.1.1.jar:na]  

源码如下（理论上应该把touch pid 放在for循环的后面---先删再建）：
    public static void createPid(String dir) throws Exception {
        File file = new File(dir);

        if (file.exists() == false) {
            file.mkdirs();
        } else if (file.isDirectory() == false) {
            throw new RuntimeException("pid dir:" + dir + " isn't directory");
        }

        String[] existPids = file.list();

        // touch pid before
        String pid = JStormUtils.process_pid();
        String pidPath = dir + File.separator + pid;
        PathUtils.touch(pidPath);
        LOG.info("Successfully touch pid  " + pidPath);

        for (String existPid : existPids) {
            try {
                JStormUtils.kill(Integer.valueOf(existPid));
                PathUtils.rmpath(dir + File.separator + existPid);
            } catch (Exception e) {
                LOG.warn(e.getMessage(), e);
            }
        }
    }

**Comment by unsleepy22** [comment]
这个没影响，下面的循环是对已经存在的pid目录进行删除而已，不会影响新创建的目录

**Comment by Fengdada** [comment]
@unsleepy22，如果先touch再删除，nimbus起不来

**Comment by unsleepy22** [comment]
有可能是跟docker相关，nimbus两次起的进程id是一样的。。

**Comment by unsleepy22** [comment]
确认了一下，在docker环境下，这的确是一个问题，我们会在年前的下一个release中修复这个bug，非常感谢～

**Comment by Fengdada** [comment]
@unsleepy22 我自己对调了下位置，好像不灵，进程id一致时还是起不来....没任何打印

**Comment by unsleepy22** [comment]
你用的是外部的数据卷么？

**Comment by Fengdada** [comment]
@unsleepy22 再问一下，release发布计划是什么？2.3啥时候发布？JStorm Streaming SQL是否会在2.3版本发布？

**Comment by Fengdada** [comment]
@unsleepy22 对，我用的持久卷

**Comment by Longda-Feng** [comment]
@Fengdada  2.2.1 过年前对外release， 这个fix 会包含进去

你如果急的话， 自己打个patch 也可以

```
// touch pid before
    String pid = JStormUtils.process_pid();
    String pidPath = dir + File.separator + pid;
    

    for (String existPid : existPids) {
        try {
            JStormUtils.kill(Integer.valueOf(existPid));
            PathUtils.rmpath(dir + File.separator + existPid);
             PathUtils.touch(pidPath);
             LOG.info("Successfully touch pid  " + pidPath);
        } catch (Exception e) {
            LOG.warn(e.getMessage(), e);
        }
    }

```

**Comment by Fengdada** [comment]
我把持久卷挂在/data目录，希望可以保存Topo的jar包信息。否则nimbus重启后，无法显示TOPO

**Comment by tongjingchen** [comment]
这个问题是不是还没解决啊
