### ISSUE TITLE
jstrom2.2.1 本地测试事务Topology 报错

### ISSUE THREAD

**Issue by superwangvip** [alibaba/jstorm#436]
java.lang.Exception: IConnection to task-0 can't be found
	at com.alibaba.jstorm.task.TaskTransfer.getConnection(TaskTransfer.java:302) [classes/:na]
	at com.alibaba.jstorm.task.TaskTransfer.serialize(TaskTransfer.java:318) [classes/:na]
	at com.alibaba.jstorm.task.TaskTransfer$TransferRunnable.onEvent(TaskTransfer.java:265) [classes/:na]
	at backtype.storm.utils.DisruptorQueueImpl.consumeBatchWhenAvailable(DisruptorQueueImpl.java:233) [classes/:na]
	at backtype.storm.utils.DisruptorQueueImpl.multiConsumeBatchWhenAvailable(DisruptorQueueImpl.java:194) [classes/:na]
	at com.alibaba.jstorm.task.TaskTransfer$TransferRunnable.run(TaskTransfer.java:251) [classes/:na]
	at com.alibaba.jstorm.callback.AsyncLoopRunnable.run(AsyncLoopRunnable.java:95) [classes/:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]

出错原因：
本地模式时在类backtype.storm.task.GeneralTopologyContext的构造方法里面将_topologyMasterId设置为了0。
	if (!StormConfig.local_mode(stormConf)) {
            _topologyMasterId = _componentToTasks.get("__topology_master").get(0);
        } else {
            _topologyMasterId = 0;
        }

此处设置为0的作用是什么？
如果想要测试本地模式的同学可以暂时改为            _topologyMasterId = _componentToTasks.get("__topology_master").get(0);

**Comment by unsleepy22** [comment]
@bastiliu

**Comment by unsleepy22** [comment]
下个版本fix这个吧，这个只影响本地运行。
