### ISSUE TITLE
jstorm 2.1.1版本是否不支持IBM JDK？Supervisor启动报错“无法获取物理内存”，如内

### ISSUE THREAD

**Issue by Fengdada** [alibaba/jstorm#467]
[INFO 2017-03-24 17:17:59 b.s.u.StormBoundedExponentialBackoffRetry:44 main] The baseSleepTimeMs [1000] the maxSleepTimeMs [30000] the maxRetries [20]
[INFO 2017-03-24 17:17:59 c.a.j.c.DefaultWatcherCallBack:40 main-EventThread] Zookeeper state update::connected,:none,null
[INFO 2017-03-24 17:18:00 b.s.u.StormBoundedExponentialBackoffRetry:44 main] The baseSleepTimeMs [1000] the maxSleepTimeMs [30000] the maxRetries [20]
[INFO 2017-03-24 17:18:00 c.a.j.c.DistributedClusterState:86 main-EventThread] Received event SyncConnected:None:null
[WARN 2017-03-24 17:18:00 c.a.j.u.JStormUtils:1258 main] Failed to get system physical memory size,
javax.management.AttributeNotFoundException: No such attribute : TotalPhysicalMemorySize
        at com.ibm.lang.management.DynamicMXBeanImpl.getAttribute(Unknown Source) ~[na:2.6 (09-15-2016)]
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getAttribute(Unknown Source) ~[na:1.8.0]
        at com.sun.jmx.mbeanserver.JmxMBeanServer.getAttribute(Unknown Source) ~[na:1.8.0]
        at com.alibaba.jstorm.utils.JStormUtils.getPhysicMemorySize(JStormUtils.java:1255) [jstorm-core-2.1.1.jar:na]
        at com.alibaba.jstorm.utils.JStormUtils.getSupervisorPortList(JStormUtils.java:1437) [jstorm-core-2.1.1.jar:na]
        at com.alibaba.jstorm.daemon.supervisor.Heartbeat.initSupervisorInfo(Heartbeat.java:105) [jstorm-core-2.1.1.jar:na]
        at com.alibaba.jstorm.daemon.supervisor.Heartbeat.＜init＞(Heartbeat.java:99) [jstorm-core-2.1.1.jar:na]
        at com.alibaba.jstorm.daemon.supervisor.Supervisor.mkSupervisor(Supervisor.java:123) [jstorm-core-2.1.1.jar:na]
        at com.alibaba.jstorm.daemon.supervisor.Supervisor.run(Supervisor.java:201) [jstorm-core-2.1.1.jar:na]
        at com.alibaba.jstorm.daemon.supervisor.Supervisor.main(Supervisor.java:237) [jstorm-core-2.1.1.jar:na]

**Comment by fengjian428** [comment]
你的jdk版本是多少呢

**Comment by Fengdada** [comment]
IBM 8.0 Docker版

**Comment by fengjian428** [comment]
1.6以下的jdk估计是不兼容的，你升级成1.7或者1.8好了
