### ISSUE TITLE
在nimbus 节点上执行 “nohup jstorm nimbus &”,时报错

### ISSUE THREAD

**Issue by RedBlackTreei** [alibaba/jstorm#471]
具体如下：
[ERROR 2017-03-30 19:07:58 c.a.j.s.FollowerRunnable:85 main] get nimbus host error!
java.lang.Exception: the hostname which Nimbus get is localhost
	at com.alibaba.jstorm.schedule.FollowerRunnable.<init>(FollowerRunnable.java:82) ~[jstorm-core-2.1.1.jar:na]
	at com.alibaba.jstorm.daemon.nimbus.NimbusServer.initFollowerThread(NimbusServer.java:275) [jstorm-core-2.1.1.jar:na]
	at com.alibaba.jstorm.daemon.nimbus.NimbusServer.launchServer(NimbusServer.java:121) [jstorm-core-2.1.1.jar:na]
	at com.alibaba.jstorm.daemon.nimbus.NimbusServer.main(NimbusServer.java:95) [jstorm-core-2.1.1.jar:na]
[ERROR 2017-03-30 19:07:58 c.a.j.d.n.NimbusServer:137 main] Fail to run nimbus 
java.lang.RuntimeException: java.lang.Exception: the hostname which Nimbus get is localhost
	at com.alibaba.jstorm.schedule.FollowerRunnable.<init>(FollowerRunnable.java:86) ~[jstorm-core-2.1.1.jar:na]
	at com.alibaba.jstorm.daemon.nimbus.NimbusServer.initFollowerThread(NimbusServer.java:275) [jstorm-core-2.1.1.jar:na]
	at com.alibaba.jstorm.daemon.nimbus.NimbusServer.launchServer(NimbusServer.java:121) [jstorm-core-2.1.1.jar:na]
	at com.alibaba.jstorm.daemon.nimbus.NimbusServer.main(NimbusServer.java:95) [jstorm-core-2.1.1.jar:na]
Caused by: java.lang.Exception: the hostname which Nimbus get is localhost
	at com.alibaba.jstorm.schedule.FollowerRunnable.<init>(FollowerRunnable.java:82) ~[jstorm-core-2.1.1.jar:na]
	... 3 common frames omitted

storm.yaml配置如下：
storm.zookeeper.servers:
    - "192.168.3.212"
 storm.zookeeper.root: "/jstorm"
 nimbus.host: "10.10.10.185"
 nimbus.host.start.supervisor: false
 storm.local.dir: "%JSTORM_HOME%/data"
 supervisor.slots.ports:
    - 6800
    - 6801
    - 6802
    - 6803

其中10.10.10.185是我本地ip

**Comment by sjq597** [comment]
你host里面配置了本机ip映射了没？
hostname -i

**Comment by RedBlackTreei** [comment]
配置了，执行hostname -i结果如下：
127.0.0.1

**Comment by sjq597** [comment]
你没详细看官方文档吧,在/ect/hosts里面加上这个
10.10.10.185　localhost

**Comment by RedBlackTreei** [comment]
谢谢提醒，我是按照安装说明来的，里面没提到这点。
能发下文档地址吗？
https://github.com/alibaba/jstorm/wiki/%E5%A6%82%E4%BD%95%E5%AE%89%E8%A3%85

**Comment by sjq597** [comment]
@RedBlackTreei 我看了github上的确实没说清楚，我看的是jstorm的官网，那个里面说的详细些:
http://www.jstorm.io/QuickStart_cn/Deploy/Standalone.html
