### ISSUE TITLE
本地运行jstorm2.1.1 任务均报这个错  Attempting to call unbound fn: #'carbonite.api/register-serializers

### ISSUE THREAD

**Issue by simon2014** [alibaba/jstorm#478]
<dependency>
            <groupId>com.twitter</groupId>
            <artifactId>carbonite</artifactId>
            <version>1.4.0</version>
        </dependency>
        <dependency>
            <groupId>com.esotericsoftware.kryo</groupId>
            <artifactId>kryo</artifactId>
            <version>2.21</version>
            <exclusions>
                <exclusion>
                    <groupId>com.esotericsoftware.minlog</groupId>
                    <artifactId>minlog</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

18:21:53.021 [EventManagerImp] ERROR c.a.j.d.supervisor.SyncProcessEvent - Failed Sync Process
java.lang.RuntimeException: java.lang.IllegalStateException: Attempting to call unbound fn: #'carbonite.api/register-serializers
	at backtype.storm.serialization.SerializationFactory.getKryo(SerializationFactory.java:75) ~[classes/:na]
	at backtype.storm.serialization.KryoValuesDeserializer.<init>(KryoValuesDeserializer.java:33) ~[classes/:na]
	at backtype.storm.serialization.KryoTupleDeserializer.<init>(KryoTupleDeserializer.java:52) ~[classes/:na]
	at com.alibaba.jstorm.daemon.worker.WorkerData.updateKryoSerializer(WorkerData.java:420) ~[classes/:na]
	at com.alibaba.jstorm.daemon.worker.WorkerData.<init>(WorkerData.java:376) ~[classes/:na]
	at com.alibaba.jstorm.daemon.worker.Worker.<init>(Worker.java:67) ~[classes/:na]
	at com.alibaba.jstorm.daemon.worker.Worker.mk_worker(Worker.java:248) ~[classes/:na]
	at com.alibaba.jstorm.daemon.supervisor.SyncProcessEvent.launchWorker(SyncProcessEvent.java:440) ~[classes/:na]
	at com.alibaba.jstorm.daemon.supervisor.SyncProcessEvent.startNewWorkers(SyncProcessEvent.java:987) ~[classes/:na]
	at com.alibaba.jstorm.daemon.supervisor.SyncProcessEvent.run(SyncProcessEvent.java:182) ~[classes/:na]
	at com.alibaba.jstorm.daemon.supervisor.SyncSupervisorEvent.run(SyncSupervisorEvent.java:191) ~[classes/:na]
	at com.alibaba.jstorm.event.EventManagerImp.run(EventManagerImp.java:71) ~[classes/:na]
	at com.alibaba.jstorm.callback.AsyncLoopRunnable.run(AsyncLoopRunnable.java:95) ~[classes/:na]
	at java.lang.Thread.run(Thread.java:724) ~[na:1.7.0_25]
Caused by: java.lang.IllegalStateException: Attempting to call unbound fn: #'carbonite.api/register-serializers
	at clojure.lang.Var$Unbound.throwArity(Var.java:43) ~[clojure-1.6.0.jar:na]
	at clojure.lang.AFn.invoke(AFn.java:36) ~[clojure-1.6.0.jar:na]
	at clojure.lang.Var.invoke(Var.java:383) ~[clojure-1.6.0.jar:na]
	at carbonite.JavaBridge.registerPrimitives(JavaBridge.java:43) ~[carbonite-1.4.0.jar:na]
	at backtype.storm.serialization.SerializationFactory.getKryo(SerializationFactory.java:72) ~[classes/:na]
	... 13 common frames omitted
本地运行jstorm2.1.1 任务均报这个错
目前怀疑是这两个jar版本不兼容 ，有碰到过类似的问题请指点下啊

**Comment by xiaohongxiedaima** [comment]
jstrom 天坑 升级到2.2.1 亲测可用
