### ISSUE TITLE
本地运行jstorm2.1.1 报这个错  ERROR c.a.j.d.supervisor.SyncProcessEvent - Failed to launchWorke

### ISSUE THREAD

**Issue by lion153375724** [alibaba/jstorm#479]
在本地模式调试时，报下面的错误，怎么解决？？
18:14:37.673 [EventManagerImp] ERROR c.a.j.d.supervisor.SyncProcessEvent - Failed to launchWorker workerId:33238aa0-c8db-4de4-8872-6264525c630b:6900
java.lang.RuntimeException: java.lang.IllegalStateException: Attempting to call unbound fn: #'carbonite.api/register-serializers
at backtype.storm.serialization.SerializationFactory.getKryo(SerializationFactory.java:75) ~[jstorm-core-2.1.1.jar:na]
at backtype.storm.serialization.KryoValuesDeserializer.(KryoValuesDeserializer.java:33) ~[jstorm-core-2.1.1.jar:na]
at backtype.storm.serialization.KryoTupleDeserializer.(KryoTupleDeserializer.java:52) ~[jstorm-core-2.1.1.jar:na]
at com.alibaba.jstorm.daemon.worker.WorkerData.updateKryoSerializer(WorkerData.java:420) ~[jstorm-core-2.1.1.jar:na]
at com.alibaba.jstorm.daemon.worker.WorkerData.(WorkerData.java:376) ~[jstorm-core-2.1.1.jar:na]
at com.alibaba.jstorm.daemon.worker.Worker.(Worker.java:67) ~[jstorm-core-2.1.1.jar:na]
at com.alibaba.jstorm.daemon.worker.Worker.mk_worker(Worker.java:248) ~[jstorm-core-2.1.1.jar:na]
at com.alibaba.jstorm.daemon.supervisor.SyncProcessEvent.launchWorker(SyncProcessEvent.java:440) [jstorm-core-2.1.1.jar:na]
at com.alibaba.jstorm.daemon.supervisor.SyncProcessEvent.startNewWorkers(SyncProcessEvent.java:987) [jstorm-core-2.1.1.jar:na]
at com.alibaba.jstorm.daemon.supervisor.SyncProcessEvent.run(SyncProcessEvent.java:182) [jstorm-core-2.1.1.jar:na]

**Comment by xiaohongxiedaima** [comment]
jstrom 天坑 升级到2.2.1 亲测可用
