### ISSUE TITLE
kryo buffer underflow exception

### ISSUE THREAD

**Issue by wuyouwuyoulian** [alibaba/jstorm#507]
异常信息： 

Async
 loop died! com.esotericsoftware.kryo.KryoException: Buffer underflow.
 at com.esotericsoftware.kryo.io.Input.require(Input.java:156) ~[kryo-2.21.jar:?]
 at com.esotericsoftware.kryo.io.Input.readLong(Input.java:650) ~[kryo-2.21.jar:?]
 at backtype.storm.tuple.MessageId.deserialize(MessageId.java:94) ~[storm-core-1.0-bdp-SNAPSHOT.jar:?]
 at backtype.storm.serialization.KryoTupleDeserializer.deserialize(KryoTupleDeserializer.java:58) ~[storm-core-1.0-bdp-SNAPSHOT.jar:?] at backtype.storm.messaging.loader$mk_receive_thread$fn__4013$fn__4014.invoke(loader.clj:44) ~[storm-core-1.0-bdp-SNAPSHOT.jar:?]
 at backtype.storm.util$async_loop$fn__467.invoke(util.clj:460) [storm-core-1.0-bdp-SNAPSHOT.jar:?] at clojure.lang.AFn.run(AFn.java:22) [clojure-1.7.0.jar:?] at java.lang.Thread.run(Thread.java:745) [?:1.7.0_67]

[ERROR] b.s.util [Thread-3-worker-receiver-thread-0] 11394_v3_20_px_jdworks 11394_v3_20_px_jdworks-30-1493095518 6721 : Halting process:

        java.lang.RuntimeException:
        at backtype.storm.util$exit_process_BANG_.doInvoke(util.clj:322) [storm-core-1.0-bdp-SNAPSHOT.jar:?]
        at clojure.lang.RestFn.invoke(RestFn.java:410) [clojure-1.7.0.jar:?]
        at backtype.storm.daemon.worker$launch_receive_thread$fn__5134.invoke(worker.clj:474) [storm-core-1.0-bdp-SNAPSHOT.jar:?]
        at backtype.storm.util$async_loop$fn__467.invoke(util.clj:470) [storm-core-1.0-bdp-SNAPSHOT.jar:?]
        at clojure.lang.AFn.run(AFn.java:22) [clojure-1.7.0.jar:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_67]

异常出现大约是隔几天出几十次，每次出现会导致集群某些IP里的某些任务的worker died，worker自动重启后依然报这个错误；但是不做任何处理，大约半小时后，这个异常就自动消失了，任务又正常运行起来。

通过异常堆栈分析，应该是messageID这个字段反序列化出现了问题，而messageid里包含一个map结构，应该是从byte流中读到了map的size，但是在继续读map的key、value值时出现了错误。

经过我们对storm源码的分析，Tuple（不管是anchor还是unanchor）在序列化时都会对messageID产生正确的封装，不至于在反序列化时出现错误。

开始怀疑是网络丢包或者错包导致的问题。但是查看网络并没有明显的波动情况。（kryo版本：2.21；netty版本：3.9.0.Final）

**Comment by unsleepy22** [comment]
你这个是不是集群中有不同版本的jstorm？
