### ISSUE TITLE
拓扑中使用user define assignment之后导致提交拓扑时报除零错误

### ISSUE THREAD

**Issue by cnkei** [alibaba/jstorm#524]
各位好，

我们的jstorm集群中有两台supervisor，A和B，各自开了一个worker的port。拓扑中有两个spout，分别用WorkerAssignment指派到了A和B上。拓扑的NumWorkers设的2。在提交拓扑的时候nimbus报了"/ by zero"的错误。

分析代码(0d146b9)后发现，是WorkerScheduler:129:putAllWorkerToSupervisor在为assignedWorkers进行分配之后，supervisor上已经没有可用的port，在141行再次getResAvailSupervisors时，supervisors为空，导致171行在做除法的时候报错了。

我将supervisor上的port设为两个，拓扑提交能通过。有趣的是，所有的component都分在了一个端口上。

请问是我worker assignment的用法有问题吗？

具体stack trace如下：

```
[ERROR 2017-05-31 15:50:41 c.a.j.d.n.TopologyAssign:187 TopologyAssign] Failed to assign topology poseidon-3-1496217039
java.lang.ArithmeticException: / by zero
        at com.alibaba.jstorm.schedule.default_assign.WorkerScheduler.putWorkerToSupervisor(WorkerScheduler.java:171) ~[jstorm-core-2.4.0.jar:na]
        at com.alibaba.jstorm.schedule.default_assign.WorkerScheduler.putAllWorkerToSupervisor(WorkerScheduler.java:151) ~[jstorm-core-2.4.0.jar:na]
        at com.alibaba.jstorm.schedule.default_assign.WorkerScheduler.getAvailableWorkers(WorkerScheduler.java:111) ~[jstorm-core-2.4.0.jar:na]
        at com.alibaba.jstorm.schedule.default_assign.DefaultTopologyScheduler.assignTasks(DefaultTopologyScheduler.java:156) ~[jstorm-core-2.4.0.jar:na]
        at com.alibaba.jstorm.daemon.nimbus.TopologyAssign.mkAssignment(TopologyAssign.java:446) [jstorm-core-2.4.0.jar:na]
        at com.alibaba.jstorm.daemon.nimbus.TopologyAssign.doTopologyAssignment(TopologyAssign.java:179) [jstorm-core-2.4.0.jar:na]
        at com.alibaba.jstorm.daemon.nimbus.TopologyAssign.run(TopologyAssign.java:134) [jstorm-core-2.4.0.jar:na]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
[ERROR 2017-05-31 15:50:41 c.a.j.d.n.ServiceHandler:371 pool-15-thread-35] Fail to submit topology, topologyId:/ by zero, uploadedJarLocation:poseidon-3-1496217039, root cause:/var/lib/jstorm/data//nimbus/inbox/a52071a8-5485-4cb8-ae60-17a1886260a1
```

PS: 最后一句报错c.a.j.d.n.ServiceHandler:371行String.format参数对应错了。

**Comment by cnkei** [comment]
我在WorkerScheduler:175加上supervisor.size() != 0的检查以后似乎能工作了。虽然Worker其实在这之前就分到所有的supervisors上了，不知道会不会有其他问题？

**Comment by cnkei** [comment]
在WorkerScheduler:175加上supervisors.size() != 0的判断之后工作了。看上去在141行就已经把worker都分配到supervisor上了，之后的分配是多余的。
