### ISSUE TITLE
特殊场景下，Worker启动失败，有没有精通的？

### ISSUE THREAD

**Issue by Fengdada** [alibaba/jstorm#532]
在这种场景下，Worker启动失败：裸设备+PaaS系统+容器，jstorm运行在容器上，容器的操作系统是Ubuntu，
而在虚机+PaaS系统+容器上运行，容器的操作系统不变，没有任何问题。
定位发现：
1.通过jps命令，可以看到大量的ProcessLauncher进程（见附1）；
2.通过top命令，可以看到这些进程的状态都是S（见附2）；
3.对进程执行jstack命令，提示进程无响应，用jstack -F，提示错误（见附3）
附件1：
jps命令可以观察到大量的ProcessLauncher，且数量在不断增加
/home/jstorm/logs # jps -v
48643 ProcessLauncher -Xms256m -Xmx256m -Djstorm.log.dir=/home/jstorm/logs -Dlogfile.name=pmmonitor-topo-vlte-worker-6912.log -Dtopology.name=pmmonitor-topo-vlte -Dlogback.configurationFile=/home/jstorm/conf/jstorm.logback.xml
49156 ProcessLauncher -Xms256m -Xmx256m -Djstorm.log.dir=/home/jstorm/logs -Dlogfile.name=pmmonitor-topo-vlte-worker-6912.log -Dtopology.name=pmmonitor-topo-vlte -Dlogback.configurationFile=/home/jstorm/conf/jstorm.logback.xml
附件2：
通过top命令看到，这些ProcessLauncher的状态都为S
/home/jstorm/logs # top
Mem: 103397232K used, 160150584K free, 4331664K shrd, 1624K buff, 24721184K cac
CPU:   2% usr   4% sys   0% nic  84% idle   9% io   0% irq   0% sirq
Load average: 25.03 24.71 26.41 5/32070 51041
  PID  PPID USER     STAT   VSZ %VSZ CPU %CPU COMMAND
39108    20 root     S    5622m   0%  39   0% java -Xms256m -Xmx256m -Djstorm.lo
39412    20 root     S    5622m   0%  29   0% java -Xms256m -Xmx256m -Djstorm.lo
20718    20 root     S    5622m   0%  44   0% java -Xms256m -Xmx256m -Djstorm.lo
41294    20 root     S    5622m   0%  35   0% java -Xms256m -Xmx256m -Djstorm.lo
30701    20 root     S    5622m   0%  46   0% java -Xms256m -Xmx256m -Djstorm.lo
39175    20 root     S    5622m   0%  31   0% java -Xms256m -Xmx256m -Djstorm.lo
39627    20 root     S    5622m   0%  46   0% java -Xms256m -Xmx256m -Djstorm.lo
39775    20 root     S    5622m   0%  34   0% java -Xms256m -Xmx256m -Djstorm.lo
39924    20 root     S    5622m   0%  44   0% java -Xms256m -Xmx256m -Djstorm.lo
40488    20 root     S    5622m   0%  43   0% java -Xms256m -Xmx256m -Djstorm.lo
41080    20 root     S    5622m   0%  39   0% java -Xms256m -Xmx256m -Djstorm.lo
43239    20 root     S    5622m   0%  35   0% java -Xms256m -Xmx256m -Djstorm.lo
41667    20 root     S    5622m   0%  30   0% java -Xms256m -Xmx256m -Djstorm.lo
44489    20 root     S    5622m   0%  44   0% java -Xms256m -Xmx256m -Djstorm.lo
42262    20 root     S    5622m   0%  29   0% java -Xms256m -Xmx256m -Djstorm.lo
45187    20 root     S    5622m   0%  44   0% java -Xms256m -Xmx256m -Djstorm.lo
42991    20 root     S    5622m   0%  42   0% java -Xms256m -Xmx256m -Djstorm.lo
44110    20 root     S    5622m   0%  50   0% java -Xms256m -Xmx256m -Djstorm.lo
44551    20 root     S    5622m   0%  33   0% java -Xms256m -Xmx256m -Djstorm.lo
附件3：
jstack -F输出
/home/jstorm/logs # jstack -F 26849
Attaching to process ID 26849, please wait...
libsaproc DEBUG: can't open shared object [heap]
libsaproc DEBUG: can't open shared object [stack:8314]
libsaproc DEBUG: can't open shared object [stack:27892]
libsaproc DEBUG: can't open shared object [stack:27891]
libsaproc DEBUG: can't open shared object [stack:27890]
libsaproc DEBUG: can't open shared object [stack:27889]
libsaproc DEBUG: can't open shared object [stack:27888]
libsaproc DEBUG: can't open shared object [stack:27887]
libsaproc DEBUG: can't open shared object [stack:27886]
libsaproc DEBUG: can't open shared object [stack:27885]
libsaproc DEBUG: can't open shared object [stack:27884]
libsaproc DEBUG: can't open shared object [stack:27883]
libsaproc DEBUG: can't open shared object [stack:27882]
libsaproc DEBUG: can't open shared object [stack:27881]
libsaproc DEBUG: can't open shared object [stack:27880]
libsaproc DEBUG: can't open shared object [stack:27879]
libsaproc DEBUG: can't open shared object [stack:27878]
libsaproc DEBUG: can't open shared object [stack:27877]
libsaproc DEBUG: can't open shared object [stack:27876]
libsaproc DEBUG: can't open shared object [stack:27875]
libsaproc DEBUG: can't open shared object [stack:27821]
libsaproc DEBUG: can't open shared object [stack:27820]
libsaproc DEBUG: can't open shared object [stack:27819]
libsaproc DEBUG: can't open shared object [stack:27812]
libsaproc DEBUG: can't open shared object [stack:27811]
libsaproc DEBUG: can't open shared object [stack:27805]
libsaproc DEBUG: can't open shared object [stack:27803]
libsaproc DEBUG: can't open shared object [stack:27802]
libsaproc DEBUG: can't open shared object [stack:27800]
libsaproc DEBUG: can't open shared object [stack:27799]
libsaproc DEBUG: can't open shared object [stack:27796]
libsaproc DEBUG: can't open shared object [stack:27795]
libsaproc DEBUG: can't open shared object [stack:27793]
libsaproc DEBUG: can't open shared object [stack:27792]
libsaproc DEBUG: can't open shared object [stack:27791]
libsaproc DEBUG: can't open shared object [stack:27789]
libsaproc DEBUG: can't open shared object [stack:27786]
libsaproc DEBUG: can't open shared object [stack:27784]
libsaproc DEBUG: can't open shared object [stack:27783]
libsaproc DEBUG: can't open shared object [stack:27782]
libsaproc DEBUG: can't open shared object [stack:27781]
libsaproc DEBUG: can't open shared object [stack:27778]
libsaproc DEBUG: can't open shared object [stack:27773]
libsaproc DEBUG: can't open shared object [stack:27771]
libsaproc DEBUG: can't open shared object [stack:27770]
libsaproc DEBUG: can't open shared object [stack:27768]
libsaproc DEBUG: can't open shared object [stack:27767]
libsaproc DEBUG: can't open shared object [stack:27765]
libsaproc DEBUG: can't open shared object [stack:27764]
libsaproc DEBUG: can't open shared object [stack:27762]
libsaproc DEBUG: can't open shared object [stack:27761]
libsaproc DEBUG: can't open shared object [stack:27759]
libsaproc DEBUG: can't open shared object [stack:27758]
libsaproc DEBUG: can't open shared object [stack:27755]
libsaproc DEBUG: can't open shared object [stack:27754]
libsaproc DEBUG: can't open shared object [stack:27752]
libsaproc DEBUG: can't open shared object [stack:27751]
libsaproc DEBUG: can't open shared object [stack:27750]
libsaproc DEBUG: can't open shared object [stack:27749]
libsaproc DEBUG: can't open shared object [stack:27748]
libsaproc DEBUG: can't open shared object [stack:27747]
libsaproc DEBUG: can't open shared object [stack:27744]
libsaproc DEBUG: can't open shared object [stack]
libsaproc DEBUG: can't open shared object [vdso]
libsaproc DEBUG: can't open shared object [vsyscall]
libsaproc DEBUG: lookup failed for symbol 'nptl_version' in obj 'libpthread.so.0
libsaproc DEBUG: can't create libthread_db agent
libsaproc DEBUG: lookup failed for symbol '__vt_10JavaThread' in obj 'libjvm.so'
libsaproc DEBUG: lookup failed for symbol '__vt_10JavaThread' in obj 'libjvm.so'
Debugger attached successfully.
Server compiler detected.
JVM version is 25.72-b15
Deadlock Detection:

No deadlocks found.

Thread 43782: (state = BLOCKED)
libsaproc DEBUG: ptrace(PTRACE_GETREGS, ...) failed for lwp 43782
Error occurred during stack walking:
sun.jvm.hotspot.debugger.DebuggerException: sun.jvm.hotspot.debugger.DebuggerExc
        at sun.jvm.hotspot.debugger.linux.LinuxDebuggerLocal$LinuxDebuggerLocalW
        at sun.jvm.hotspot.debugger.linux.LinuxDebuggerLocal.getThreadIntegerReg
        at sun.jvm.hotspot.debugger.linux.LinuxThread.getContext(LinuxThread.jav
        at sun.jvm.hotspot.runtime.linux_amd64.LinuxAMD64JavaThreadPDAccess.getC
        at sun.jvm.hotspot.runtime.JavaThread.getCurrentFrameGuess(JavaThread.ja
        at sun.jvm.hotspot.runtime.JavaThread.getLastJavaVFrameDbg(JavaThread.ja
        at sun.jvm.hotspot.tools.StackTrace.run(StackTrace.java:86)
        at sun.jvm.hotspot.tools.StackTrace.run(StackTrace.java:45)
        at sun.jvm.hotspot.tools.JStack.run(JStack.java:66)
        at sun.jvm.hotspot.tools.Tool.startInternal(Tool.java:260)
        at sun.jvm.hotspot.tools.Tool.start(Tool.java:223)
        at sun.jvm.hotspot.tools.Tool.execute(Tool.java:118)
        at sun.jvm.hotspot.tools.JStack.main(JStack.java:92)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.tools.jstack.JStack.runJStackTool(JStack.java:140)
        at sun.tools.jstack.JStack.main(JStack.java:106)
Caused by: sun.jvm.hotspot.debugger.DebuggerException: get_thread_regs failed fo
        at sun.jvm.hotspot.debugger.linux.LinuxDebuggerLocal.getThreadIntegerReg
        at sun.jvm.hotspot.debugger.linux.LinuxDebuggerLocal.access$800(LinuxDeb
        at sun.jvm.hotspot.debugger.linux.LinuxDebuggerLocal$1GetThreadIntegerRe
        at sun.jvm.hotspot.debugger.linux.LinuxDebuggerLocal$LinuxDebuggerLocalW

**Comment by easonwood** [comment]
我也遇到了
这个ProcessLauncher是生成Worker的过渡进程吧？
提交任务后ProcessLauncher一直在，一直占用6800端口，Worker里日志都是6800拒接连接。
而且kill topology也杀不掉ProcessLauncher，只会干掉Worker。
重启Supervisor后还是这样
