### ISSUE TITLE
storm-kafka的NullPointer。。

### ISSUE THREAD

**Issue by easonwood** [alibaba/jstorm#546]
我用的jstorm版本 2.2.1。topology中KafkaSpout来自 org.apache.storm.storm-kafka (版本0.9.2-incubating)。在重启拓扑的时候，经常看到以下日志，UI会报错 worker is dead on xx.xx.xx.xx。可是实际计算并没受到影响。

[ERROR 2017-06-28 14:52:43 c.a.j.t.e.BaseExecutors:182 NginxOperationSpout:20-MultipleThreadSpoutExecutors] Init error
java.lang.NullPointerException: null
        at backtype.storm.task.TopologyContext.registerMetric(TopologyContext.java:334) ~[jstorm-core-2.2.1.jar:na]
        at storm.kafka.KafkaSpout.open(KafkaSpout.java:97) ~[stormjar.jar:na]
        at com.alibaba.jstorm.task.execute.spout.SpoutExecutors.init(SpoutExecutors.java:167) ~[jstorm-core-2.2.1.jar:na]
        at com.alibaba.jstorm.task.execute.spout.MultipleThreadSpoutExecutors.init(MultipleThreadSpoutExecutors.java:58) [jstorm-core-2.2.1.jar:na]
        at com.alibaba.jstorm.task.execute.BaseExecutors.initWrapper(BaseExecutors.java:173) ~[jstorm-core-2.2.1.jar:na]
        at com.alibaba.jstorm.task.execute.spout.MultipleThreadSpoutExecutors.run(MultipleThreadSpoutExecutors.java:70) [jstorm-core-2.2.1.jar:na]
        at com.alibaba.jstorm.callback.AsyncLoopRunnable.run(AsyncLoopRunnable.java:95) [jstorm-core-2.2.1.jar:na]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
[ERROR 2017-06-28 14:52:43 c.a.j.t.e.TaskReportError:46 NginxOperationSpout:20-MultipleThreadSpoutExecutors] Report error to /ZK/taskerrors/NginxOperationTopology-60-1498632754/20
java.lang.NullPointerException: null
        at backtype.storm.task.TopologyContext.registerMetric(TopologyContext.java:334) ~[jstorm-core-2.2.1.jar:na]
        at storm.kafka.KafkaSpout.open(KafkaSpout.java:97) ~[stormjar.jar:na]
        at com.alibaba.jstorm.task.execute.spout.SpoutExecutors.init(SpoutExecutors.java:167) ~[jstorm-core-2.2.1.jar:na]
        at com.alibaba.jstorm.task.execute.spout.MultipleThreadSpoutExecutors.init(MultipleThreadSpoutExecutors.java:58) [jstorm-core-2.2.1.jar:na]
        at com.alibaba.jstorm.task.execute.BaseExecutors.initWrapper(BaseExecutors.java:173) ~[jstorm-core-2.2.1.jar:na]
        at com.alibaba.jstorm.task.execute.spout.MultipleThreadSpoutExecutors.run(MultipleThreadSpoutExecutors.java:70) [jstorm-core-2.2.1.jar:na]
        at com.alibaba.jstorm.callback.AsyncLoopRunnable.run(AsyncLoopRunnable.java:95) [jstorm-core-2.2.1.jar:na]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]

**Comment by MuskteerAthos** [comment]
没人跟帖呢 我也遇到了

**Comment by kjzxzzh** [comment]
> 没人跟帖呢 我也遇到了

我也遇到了，请问怎么解决的呢？
