### ISSUE TITLE
Jstorm与Storm兼容性问题

### ISSUE THREAD

**Issue by Ruguo** [alibaba/jstorm#547]
将原先运行在Storm0.9.6上的应用迁移提交到JStorm2.2.1上，会报Runtime Exception，请问Storm和JStorm在兼容性上如何

**Comment by Ruguo** [comment]
刚开始报的错误：java.lang.NoClassDefFoundError: org/apache/storm/guava/base/Preconditions , at 2017-07-12 14:10
	at com.xxx.xxx.Spout.open(XxxSpout.java:59)
	at com.alibaba.jstorm.task.execute.spout.SpoutExecutors.init(SpoutExecutors.java:167)
	at com.alibaba.jstorm.task.execute.spout.MultipleThreadSpoutExecutors.init(MultipleThreadSpoutExecutors.java:58)
	at com.alibaba.jstorm.task.execute.BaseExecutors.initWrapper(BaseExecutors.java:173)
	at com.alibaba.jstorm.task.execute.spout.MultipleThreadSpoutExecutors.run(MultipleThreadSpoutExecutors.java:70)
	at com.alibaba.jstorm.callback.AsyncLoopRunnable.run(AsyncLoopRunnable.java:95)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.apache.storm.guava.base.Preconditions
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at backtype.storm.utils.WorkerClassLoader.loadClass(WorkerClassLoader.java:98)
	... 10 mor
将缺少的类加入jar包后，又出现如下错误：
java.lang.RuntimeException: null
	at com.xxx.xxx.execute(xxx.java:135) ~[stormjar.jar:na]
	at backtype.storm.topology.BasicBoltExecutor.execute(BasicBoltExecutor.java:49) ~[jstorm-core-2.2.1.jar:na]
	at com.alibaba.jstorm.task.execute.BoltExecutors.processTupleEvent(BoltExecutors.java:248) [jstorm-core-2.2.1.jar:na]
	at com.alibaba.jstorm.task.execute.BoltExecutors.onEvent(BoltExecutors.java:184) [jstorm-core-2.2.1.jar:na]
	at backtype.storm.utils.DisruptorQueueImpl.consumeBatchToCursor(DisruptorQueueImpl.java:261) [jstorm-core-2.2.1.jar:na]
	at backtype.storm.utils.DisruptorQueueImpl.consumeBatchWhenAvailable(DisruptorQueueImpl.java:226) [jstorm-core-2.2.1.jar:na]
	at backtype.storm.utils.DisruptorQueueImpl.consumeBatchWhenAvailable(DisruptorQueueImpl.java:185) [jstorm-core-2.2.1.jar:na]
	at com.alibaba.jstorm.task.execute.BoltExecutors.run(BoltExecutors.java:148) [jstorm-core-2.2.1.jar:na]
	at com.alibaba.jstorm.callback.AsyncLoopRunnable.run(AsyncLoopRunnable.java:95) [jstorm-core-2.2.1.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_67]

应用在storm上运行正常稳定，但迁移至Jstorm上出现各种问题，二者在兼容性存在问题？

**Comment by sjq597** [comment]
你是直接就把原来的jar包提交吗?一般我的做法是再编译一遍然后再提交

**Comment by Ruguo** [comment]
恩恩，重新编译后再提交，但是感觉两者jar存在问题

**Comment by longdafeng** [comment]
jstorm 把所有依赖的dependency 给做shade（开源主流都是这种做法， storm 也是这样，但不彻底）， 这样可以避免 用户的依赖和jstorm的依赖发生冲突， 比如用户使用thrift 0.7， 但jstorm 使用thrift 0.9

这样当用户需要使用一些jstorm的依赖的时候， 用户需要自己再引入这些依赖
