### ISSUE TITLE
很多线程处于lock状态

### ISSUE THREAD

**Issue by dengbo** [alibaba/jstorm#552]
在jstack里看到好多这种parking的线程，这是任务出了啥问题吗？
"Handle:193-TransferRunnable-0" #65 prio=5 os_prio=0 tid=0x00007fe510006000 nid=0x31424 runnable [0x00007fe571ee1000]
java.lang.Thread.State: TIMED_WAITING (parking)
at sun.misc.Unsafe.park(Native Method)
- parking to wait for <0x00000000c0378480> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
at shade.storm.com.lmax.disruptor.TimeoutBlockingWaitStrategy.waitFor(TimeoutBlockingWaitStrategy.java:37)
at shade.storm.com.lmax.disruptor.ProcessingSequenceBarrier.waitFor(ProcessingSequenceBarrier.java:55)
at backtype.storm.utils.DisruptorQueueImpl.retreiveAvailableBatch(DisruptorQueueImpl.java:276)
- locked <0x00000000c0362b98> (a backtype.storm.utils.DisruptorQueueImpl)
at backtype.storm.utils.DisruptorQueueImpl.consumeBatchWhenAvailable(DisruptorQueueImpl.java:229)
at backtype.storm.utils.DisruptorQueueImpl.multiConsumeBatchWhenAvailable(DisruptorQueueImpl.java:194)
at com.alibaba.jstorm.task.TaskTransfer$TransferRunnable.run(TaskTransfer.java:251)
at com.alibaba.jstorm.callback.AsyncLoopRunnable.run(AsyncLoopRunnable.java:95)
at java.lang.Thread.run(Thread.java:748)

"KafkaSpout:353-TransferRunnable-0" #64 prio=5 os_prio=0 tid=0x00007fe504003800 nid=0x31423 runnable [0x00007fe571fe2000]
java.lang.Thread.State: TIMED_WAITING (parking)
at sun.misc.Unsafe.park(Native Method)
- parking to wait for <0x00000000c02fee58> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
at shade.storm.com.lmax.disruptor.TimeoutBlockingWaitStrategy.waitFor(TimeoutBlockingWaitStrategy.java:37)
at shade.storm.com.lmax.disruptor.ProcessingSequenceBarrier.waitFor(ProcessingSequenceBarrier.java:55)
at backtype.storm.utils.DisruptorQueueImpl.retreiveAvailableBatch(DisruptorQueueImpl.java:276)
- locked <0x00000000c02da1e8> (a backtype.storm.utils.DisruptorQueueImpl)
at backtype.storm.utils.DisruptorQueueImpl.consumeBatchWhenAvailable(DisruptorQueueImpl.java:229)
at backtype.storm.utils.DisruptorQueueImpl.multiConsumeBatchWhenAvailable(DisruptorQueueImpl.java:194)
at com.alibaba.jstorm.task.TaskTransfer$TransferRunnable.run(TaskTransfer.java:251)
at com.alibaba.jstorm.callback.AsyncLoopRunnable.run(AsyncLoopRunnable.java:95)
at java.lang.Thread.run(Thread.java:748)

"pool-7-thread-5" #59 prio=5 os_prio=0 tid=0x00007fe55c007800 nid=0x313b6 waiting on condition [0x00007fe5724e7000]
java.lang.Thread.State: TIMED_WAITING (parking)
at sun.misc.Unsafe.park(Native Method)
- parking to wait for <0x00000000c042bb28> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
at java.util.concurrent.ArrayBlockingQueue.poll(ArrayBlockingQueue.java:418)
at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1066)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:748)

**Comment by longdafeng** [comment]
这是正常的
当没数据时， disrupt 在等待数据或其他blocking queue在等待数据， 就是这个状态
