### ISSUE TITLE
jstorm supervisor无法启动woker

### ISSUE THREAD

**Issue by zhulongchao** [alibaba/jstorm#556]
1.docker环境，jstorm版本：2.2.1

2.通过java -Xms...手动提交，是可以创建worker的，通过jstorm jar 提交不行

3.jstack定位发现是 com.alibaba.jstorm.utils.ProcessLauncher 的main函数执行 

    `System.out.println("Properties:" + System.getProperties())` 

   时block了(native方法write时block了，cpu的占用率不高，jstack的线程状态Runnable不正确)
   jstack 信息如下
   `   java.lang.Thread.State: RUNNABLE
	at java.io.FileOutputStream.writeBytes(Native Method)
	at java.io.FileOutputStream.write(FileOutputStream.java:326)
	at java.io.BufferedOutputStream.write(BufferedOutputStream.java:122)
	- locked <0x00000000fab1f388> (a java.io.BufferedOutputStream)
	at java.io.PrintStream.write(PrintStream.java:480)
	- locked <0x00000000fab1f2d8> (a java.io.PrintStream)
	at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
	at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:291)
	at sun.nio.cs.StreamEncoder.flushBuffer(StreamEncoder.java:104)
	- locked <0x00000000fab1f5b0> (a java.io.OutputStreamWriter)
	at java.io.OutputStreamWriter.flushBuffer(OutputStreamWriter.java:185)
	at java.io.PrintStream.write(PrintStream.java:527)
	- locked <0x00000000fab1f2d8> (a java.io.PrintStream)
	at java.io.PrintStream.print(PrintStream.java:669)
	at java.io.PrintStream.println(PrintStream.java:806)
	- locked <0x00000000fab1f2d8> (a java.io.PrintStream)
	at com.alibaba.jstorm.utils.ProcessLauncher.main(ProcessLauncher.java:134)`

4.打印的properties信息长度为4278，发现把properties信息调整到2000以下，能够自动启动woker

麻烦大神帮忙解答下哈

**Comment by longdafeng** [comment]
可以加一个配置关掉  ProcessLauncher， 直接让supervisor 启动worker， 
process.launcher.enable: false

现在是supervisor 启动ProcessLauncher， ProcessLauncher 再启动worker， 启动worker后，ProcessLauncher会自杀。

**Comment by zhulongchao** [comment]
谢谢您的回复，ProcessLauncher在main函数的入口，system.out.println时阻塞了，还没启动LauncherThread，ProcessLaucher的 JStormUtils.haltProcess也应该还没执行吧。

为什么在 ProcessLauncher的main函数入口处，执行system.out.println时，为什么阻塞，解释不通哈

**Comment by wxl24life** [comment]
@zhulongchao @longdafeng 遇到了同样的问题，ProcessLauncher 线程一直是 RUNNABLE 状态，像是阻塞在了内部的 system.out.println 。有一个疑问，ProcessLauncher 类里的 system.out 输出位置是哪里..
