### ISSUE TITLE
jstorm在压力比较大时出现奇怪的错误

### ISSUE THREAD

**Issue by whaon** [alibaba/jstorm#575]
```
[ERROR 2017-09-06 02:41:16 c.a.j.z.Zookeeper:165 pool-6-thread-2] zookeeper getdata for path/taskerrors/xxx-17-1504146012/last_error
shade.storm.org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /taskerrors/xxx-17-1504146012/last_error
	at shade.storm.org.apache.zookeeper.KeeperException.create(KeeperException.java:111) ~[jstorm-core-2.4.0.jar:na]
	at shade.storm.org.apache.zookeeper.KeeperException.create(KeeperException.java:51) ~[jstorm-core-2.4.0.jar:na]
	at shade.storm.org.apache.zookeeper.ZooKeeper.getData(ZooKeeper.java:1155) ~[jstorm-core-2.4.0.jar:na]
	at shade.storm.org.apache.curator.framework.imps.GetDataBuilderImpl$4.call(GetDataBuilderImpl.java:302) ~[jstorm-core-2.4.0.jar:na]
	at shade.storm.org.apache.curator.framework.imps.GetDataBuilderImpl$4.call(GetDataBuilderImpl.java:291) ~[jstorm-core-2.4.0.jar:na]
	at shade.storm.org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:107) ~[jstorm-core-2.4.0.jar:na]
	at shade.storm.org.apache.curator.framework.imps.GetDataBuilderImpl.pathInForeground(GetDataBuilderImpl.java:287) ~[jstorm-core-2.4.0.jar:na]
	at shade.storm.org.apache.curator.framework.imps.GetDataBuilderImpl.forPath(GetDataBuilderImpl.java:279) ~[jstorm-core-2.4.0.jar:na]
	at shade.storm.org.apache.curator.framework.imps.GetDataBuilderImpl.forPath(GetDataBuilderImpl.java:41) ~[jstorm-core-2.4.0.jar:na]
	at com.alibaba.jstorm.zk.Zookeeper.getData(Zookeeper.java:161) ~[jstorm-core-2.4.0.jar:na]
	at com.alibaba.jstorm.cluster.DistributedClusterState.get_data(DistributedClusterState.java:138) [jstorm-core-2.4.0.jar:na]
	at com.alibaba.jstorm.cluster.StormZkClusterState.getObject(StormZkClusterState.java:160) [jstorm-core-2.4.0.jar:na]
	at com.alibaba.jstorm.cluster.StormZkClusterState.removeLastErrInfoDuration(StormZkClusterState.java:438) [jstorm-core-2.4.0.jar:na]
	at com.alibaba.jstorm.cluster.StormZkClusterState.report_task_error(StormZkClusterState.java:417) [jstorm-core-2.4.0.jar:na]
	at com.alibaba.jstorm.cluster.StormZkClusterState.report_task_error(StormZkClusterState.java:383) [jstorm-core-2.4.0.jar:na]
	at com.alibaba.jstorm.task.error.TaskReportError.report(TaskReportError.java:66) [jstorm-core-2.4.0.jar:na]
	at com.alibaba.jstorm.task.error.TaskReportErrorAndDie.report(TaskReportErrorAndDie.java:50) [jstorm-core-2.4.0.jar:na]
	at com.alibaba.jstorm.daemon.worker.timer.TaskHeartbeatTrigger.checkExecuteThreadHb(TaskHeartbeatTrigger.java:160) [jstorm-core-2.4.0.jar:na]
	at com.alibaba.jstorm.daemon.worker.timer.TaskHeartbeatTrigger.run(TaskHeartbeatTrigger.java:101) [jstorm-core-2.4.0.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_121]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_121]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_121]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
[ERROR 2017-09-06 02:41:16 c.a.j.t.e.TaskReportError:68 pool-6-thread-1] Failed to update error to /ZK/taskerrors/xxx-17-1504146012/5
shade.storm.org.apache.zookeeper.KeeperException$NodeExistsException: KeeperErrorCode = NodeExists for /taskerrors/xxx-17-1504146012/last_error
	at shade.storm.org.apache.zookeeper.KeeperException.create(KeeperException.java:119) ~[jstorm-core-2.4.0.jar:na]
	at shade.storm.org.apache.zookeeper.KeeperException.create(KeeperException.java:51) ~[jstorm-core-2.4.0.jar:na]
	at shade.storm.org.apache.zookeeper.ZooKeeper.create(ZooKeeper.java:783) ~[jstorm-core-2.4.0.jar:na]
	at shade.storm.org.apache.curator.framework.imps.CreateBuilderImpl$11.call(CreateBuilderImpl.java:676) ~[jstorm-core-2.4.0.jar:na]
	at shade.storm.org.apache.curator.framework.imps.CreateBuilderImpl$11.call(CreateBuilderImpl.java:660) ~[jstorm-core-2.4.0.jar:na]
	at shade.storm.org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:107) ~[jstorm-core-2.4.0.jar:na]
	at shade.storm.org.apache.curator.framework.imps.CreateBuilderImpl.pathInForeground(CreateBuilderImpl.java:656) ~[jstorm-core-2.4.0.jar:na]
	at shade.storm.org.apache.curator.framework.imps.CreateBuilderImpl.protectedPathInForeground(CreateBuilderImpl.java:441) ~[jstorm-core-2.4.0.jar:na]
	at shade.storm.org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:431) ~[jstorm-core-2.4.0.jar:na]
	at shade.storm.org.apache.curator.framework.imps.CreateBuilderImpl$3.forPath(CreateBuilderImpl.java:239) ~[jstorm-core-2.4.0.jar:na]
	at shade.storm.org.apache.curator.framework.imps.CreateBuilderImpl$3.forPath(CreateBuilderImpl.java:193) ~[jstorm-core-2.4.0.jar:na]
	at com.alibaba.jstorm.zk.Zookeeper.createNode(Zookeeper.java:95) ~[jstorm-core-2.4.0.jar:na]
	at com.alibaba.jstorm.cluster.DistributedClusterState.set_data(DistributedClusterState.java:183) ~[jstorm-core-2.4.0.jar:na]
	at com.alibaba.jstorm.cluster.StormZkClusterState.setObject(StormZkClusterState.java:191) ~[jstorm-core-2.4.0.jar:na]
	at com.alibaba.jstorm.cluster.StormZkClusterState.setLastErrInfo(StormZkClusterState.java:470) ~[jstorm-core-2.4.0.jar:na]
	at com.alibaba.jstorm.cluster.StormZkClusterState.report_task_error(StormZkClusterState.java:432) ~[jstorm-core-2.4.0.jar:na]
	at com.alibaba.jstorm.cluster.StormZkClusterState.report_task_error(StormZkClusterState.java:383) ~[jstorm-core-2.4.0.jar:na]
	at com.alibaba.jstorm.task.error.TaskReportError.report(TaskReportError.java:66) ~[jstorm-core-2.4.0.jar:na]
	at com.alibaba.jstorm.task.error.TaskReportErrorAndDie.report(TaskReportErrorAndDie.java:50) [jstorm-core-2.4.0.jar:na]
	at com.alibaba.jstorm.daemon.worker.timer.TaskHeartbeatTrigger.checkExecuteThreadHb(TaskHeartbeatTrigger.java:160) [jstorm-core-2.4.0.jar:na]
	at com.alibaba.jstorm.daemon.worker.timer.TaskHeartbeatTrigger.run(TaskHeartbeatTrigger.java:101) [jstorm-core-2.4.0.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_121]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_121]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_121]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
[ERROR 2017-09-06 02:42:26 c.a.j.t.e.TaskReportError:64 pool-6-thread-3] Report error to /ZK/taskerrors/xxx-17-1504146012/20: No response from Task-20, last report time(sec) is 1504664526
[ERROR 2017-09-06 02:42:36 c.a.j.t.e.TaskReportError:64 pool-6-thread-3] Report error to /ZK/taskerrors/xxx-17-1504146012/29: No response from Task-29, last report time(sec) is 1504664526
[ERROR 2017-09-06 02:42:56 c.a.j.t.e.TaskReportError:64 pool-6-thread-2] Report error to /ZK/taskerrors/xxx-17-1504146012/13: No response from Task-13, last report time(sec) is 1504664526
[ERROR 2017-09-06 02:43:06 c.a.j.t.e.TaskReportError:64 pool-6-thread-4] Report error to /ZK/taskerrors/xxx-17-1504146012/17: No response from Task-17, last report time(sec) is 1504664526
[ERROR 2017-09-06 02:43:16 c.a.j.t.e.TaskReportError:64 pool-6-thread-1] Report error to /ZK/taskerrors/xxx-17-1504146012/24: No response from Task-24, last report time(sec) is 1504664526
[ERROR 2017-09-06 02:43:16 c.a.j.t.e.TaskReportError:64 pool-6-thread-3] Report error to /ZK/taskerrors/xxx-17-1504146012/33: No response from Task-33, last report time(sec) is 1504664526
[ERROR 2017-09-06 02:43:16 c.a.j.t.e.TaskReportError:64 pool-6-thread-4] Report error to /ZK/taskerrors/xxx-17-1504146012/9: No response from Task-9, last report time(sec) is 1504664526
[ERROR 2017-09-06 02:43:16 c.a.j.t.e.TaskReportError:64 pool-6-thread-2] Report error to /ZK/taskerrors/xxx-17-1504146012/5: No response from Task-5, last report time(sec) is 1504664526
```

看的而是说zookeeper没有node，zookeeper的根节点确实没有一个叫做/ZK的，但是这个也没地方配置啊

**Comment by longdafeng** [comment]
在你的storm.yaml 里面zk 的根目录是/zk， 怀疑是你storm里面配置zk地址出错
