### ISSUE TITLE
jstorm 更新配置文件出错

### ISSUE THREAD

**Issue by Alxiaoyu** [alibaba/jstorm#585]
使用: jstorm  update_topology  TopologyName  -conf configPath 更新配置文件出现，
[ERROR 2017-10-31 17:09:23 c.a.j.d.w.Worker:439 main] Failed to create worker: topologyId:poseidon-5-1509440278, port:6700, workerId:bc218bfa-7a57-4cc5-a844-1c9b8d61d4fa, jarPath:/var/lib/jstorm/data//supervisor/stormdist/poseidon-5-1509440278/stormjar.jar

java.lang.RuntimeException: java.lang.ClassNotFoundException: cn.net.yunshan.poseidon.app.arp_spoof_app.ArpSpoofMeter
	at backtype.storm.serialization.SerializationFactory.getKryo(SerializationFactory.java:96) ~[jstorm-core-2.4.0.jar:na]
	at backtype.storm.serialization.KryoValuesDeserializer.<init>(KryoValuesDeserializer.java:34) ~[jstorm-core-2.4.0.jar:na]
	at backtype.storm.serialization.KryoTupleDeserializer.<init>(KryoTupleDeserializer.java:54) ~[jstorm-core-2.4.0.jar:na]
	at com.alibaba.jstorm.daemon.worker.WorkerData.updateKryoSerializer(WorkerData.java:472) ~[jstorm-core-2.4.0.jar:na]
	at com.alibaba.jstorm.daemon.worker.WorkerData.<init>(WorkerData.java:426) ~[jstorm-core-2.4.0.jar:na]
	at com.alibaba.jstorm.daemon.worker.Worker.<init>(Worker.java:68) ~[jstorm-core-2.4.0.jar:na]
	at com.alibaba.jstorm.daemon.worker.Worker.mk_worker(Worker.java:237) ~[jstorm-core-2.4.0.jar:na]
	at com.alibaba.jstorm.daemon.worker.Worker.main(Worker.java:431) ~[jstorm-core-2.4.0.jar:na]
Caused by: java.lang.ClassNotFoundException: cn.net.yunshan.poseidon.app.arp_spoof_app.ArpSpoofMeter
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_151]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_151]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335) ~[na:1.8.0_151]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_151]
	at java.lang.Class.forName0(Native Method) ~[na:1.8.0_151]
	at java.lang.Class.forName(Class.java:348) ~[na:1.8.0_151]
	at backtype.storm.serialization.SerializationFactory.getKryo(SerializationFactory.java:82) ~[jstorm-core-2.4.0.jar:na]
	... 7 common frames omitted

supervisor上的jar包没有内容，如果更新时加上jar包就没问题。

**Comment by Alxiaoyu** [comment]
原来在这里发bug是没人看的
