### ISSUE TITLE
2.4.0 本地调试报错

### ISSUE THREAD

**Issue by kevin19931015** [alibaba/jstorm#596]
错误：
java.lang.NoClassDefFoundError: backtype/storm/topology/IRichSpout
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: backtype.storm.topology.IRichSpout
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main"

**Comment by DDDDh** [comment]
Can you solve it now?

**Comment by DDDDh** [comment]
I try to delete the <scope>provided</scope> in pom but isn't work.
Somehow I solve it by reimport the project with gradle.

**Comment by hektor8603** [comment]
how to solve it？ @kevin19931015
