### ISSUE TITLE
NimbusServer 进程起来的情况下执行jstorm jar *** 提示 no alive nimbus

### ISSUE THREAD

**Issue by zou79189747** [alibaba/jstorm#644]
详细错误信息如下：
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: Failed to get master from ZK.
	at backtype.storm.command.list.main(list.java:62)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Failed to get master from ZK.
	at backtype.storm.utils.NimbusClient.getConfiguredClientAs(NimbusClient.java:80)
	at backtype.storm.utils.NimbusClient.getConfiguredClient(NimbusClient.java:45)
	at backtype.storm.utils.NimbusClient.getConfiguredClient(NimbusClient.java:40)
	at backtype.storm.command.list.main(list.java:46)
Caused by: java.lang.RuntimeException: Failed to get master from ZK.
	at backtype.storm.security.auth.ThriftClient.getMaster(ThriftClient.java:131)
	at backtype.storm.security.auth.ThriftClient.<init>(ThriftClient.java:87)
	at backtype.storm.utils.NimbusClient.<init>(NimbusClient.java:94)
	at backtype.storm.utils.NimbusClient.getConfiguredClientAs(NimbusClient.java:76)
	... 3 more
Caused by: java.lang.RuntimeException: No alive nimbus 
	at backtype.storm.security.auth.ThriftClient.getMasterByZk(ThriftClient.java:103)
	at backtype.storm.security.auth.ThriftClient.getMaster(ThriftClient.java:128)

我的流程是这样，先nohup启动nimbus 等待10s nohup启动supervisor 等待30s左右运行jstorm jar , 报这个错误，我想知道使用jps命令看到NimbusServer 存在了 是代表nimbus 可用了吗，还是需要又个等待时间，中间是怎么样的一个流程

**Comment by vipsql** [comment]
是不是zookeeper挂了?

**Comment by saltyfishGeGe** [comment]
zk那块应该是没配置对。 Config.STORM_ZOOKEEPER_ROOT默认是/jstorm,  Config.STORM_ZOOKEEPER_SERVERS是localhost。你改成自己的zk配置试试
