### ISSUE TITLE
与 spring 整合过程中，jstorm 2.1.1 和 spring starter 依赖冲突

### ISSUE THREAD

**Issue by yuying0329** [alibaba/jstorm#655]
jstorm 整合 springboot 过程中产生了依赖冲突，报错如下：

java.lang.NoSuchMethodError: org.apache.curator.utils.PathUtils.validatePath(Ljava/lang/String;)Ljava/lang/String; , at 2019-01-08 10:44
at org.apache.curator.framework.recipes.cache.ChildData.(ChildData.java:33)
at org.apache.curator.framework.recipes.cache.PathChildrenCache.(PathChildrenCache.java:90)
at com.keep.data.jodis.RoundRobinJedisPool.(RoundRobinJedisPool.java:207)
at com.keep.data.jodis.RoundRobinJedisPool.(RoundRobinJedisPool.java:157)
at com.keep.data.jodis.RoundRobinJedisPool.(RoundRobinJedisPool.java:131)
at com.keep.spring.boot.codis.MultipleCodisBeanDefinitionRegistrar.registerCodisBeanDefinition(MultipleCodisBeanDefinitionRegistrar.java:67)
at com.keep.spring.boot.codis.MultipleCodisBeanDefinitionRegistrar.registerDynamicCodisBeanDefinition(MultipleCodisBeanDefinitionRegistrar.java:60)
at com.keep.spring.boot.codis.MultipleCodisBeanDefinitionRegistrar.registerBeanDefinitions(MultipleCodisBeanDefinitionRegistrar.java:55)
at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsFromRegistrars(ConfigurationClassBeanDefinitionReader.java:359)
at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForConfigurationClass(ConfigurationClassBeanDefinitionReader.java:143)
at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitions(ConfigurationClassBeanDefinitionReader.java:116)
at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:320)
at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:228)
at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:272)
at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:92)
at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:687)
at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:525)
at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693)
at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360)
at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
at com.keep.venom.storm.VenomStormApplication.run(VenomStormApplication.java:32)
at com.keep.venom.storm.bolt.UserRegisteredBolt.prepare(UserRegisteredBolt.java:56)
at backtype.storm.topology.BasicBoltExecutor.prepare(BasicBoltExecutor.java:42)
at com.alibaba.jstorm.task.execute.BoltExecutors.init(BoltExecutors.java:118)
at com.alibaba.jstorm.task.execute.BaseExecutors.initWrapper(BaseExecutors.java:154)
at com.alibaba.jstorm.task.execute.BoltExecutors.run(BoltExecutors.java:131)
at com.alibaba.jstorm.callback.AsyncLoopRunnable.run(AsyncLoopRunnable.java:95)
at java.lang.Thread.run(Thread.java:745
Worker is dead on 172.20.4.113:6901,20190108104440, at 2019-01-08 10:44

jstorm 版本是2.1.1，spring 使用 spring starter 配置，产生冲突的包是 org.apache.curator:curator-client，请问怎么解决呢？升级 jstorm 版本吗？

**Comment by hdyang12** [comment]
解决了吗？有同样的问题
